CREATE TABLE BARCOS
(
	MATRICULA VARCHAR (10),
	NOMBRE VARCHAR (20),
	CLASE VARCHAR(10),
	ARMADOR VARCHAR(10),
	CAPACIDAD NUMERIC (10),
	NACIONALIDAD VARCHAR(10),
	CONSTRAINT PK_BARCOS PRIMARY KEY (MATRICULA)
);
CREATE TABLE ESPECIE
(
	CODIGO VARCHAR(10),
	NOMBRE VARCHAR(20),
	TIPO VARCHAR(10),
	CUPOPORBARCO NUMERIC(10),
	CALADERO_PRINCIPAL VARCHAR(10),
	CONSTRAINT PK_ESPECIE PRIMARY KEY (CODIGO)
);
CREATE TABLE LOTES
(
	CODIGO VARCHAR(10),
	MATRICULA VARCHAR(10),
	NUMKILOS DECIMAL(10,2),
	PRECIOPORKILOSALIDA DECIMAL (10,2),
	PRECIOPORKILOADJUDICADO DECIMAL (10,2),
	FECHAVENTA DATE NOT NULL,
	COD_ESPECIE VARCHAR(10),
	CONSTRAINT PK_LOTE PRIMARY KEY (CODIGO),
	CONSTRAINT FK1_LOTE FOREIGN KEY (CODIGO) REFERENCES ESPECIE(CODIGO),
	CONSTRAINT FK2_LOTE FOREIGN KEY (MATRICULA) REFERENCES BARCOS(MATRICULA) ON DELETE CASCADE
);
CREATE TABLE CALADERO
(
	CODIGO VARCHAR(10),
	NOMBRE VARCHAR(20),
	UBICACION VARCHAR(25),
	ESPECIE_PRINCIPAL VARCHAR(10)
);
CREATE TABLE FECHA_CAPTURAS_PERMITIDAS
(
	COD_ESPECIE VARCHAR(10),
	COD_CALADERO VARCHAR(10),
	FECHA_INICIAL DATE,
	FECHA_FINAL DATE
);

ALTER TABLE BARCOS ADD CONSTRAINT CHK_MATRICULA CHECK (REGEXP_LIKE(MATRICULA, '^[A-Z]{2}-[0-9]{4}$'));

ALTER TABLE CALADERO ADD CONSTRAINT PK_CALADERO PRIMARY KEY (CODIGO);
ALTER TABLE CALADERO ADD CONSTRAINT FK1_CALADERO FOREIGN KEY (CODIGO) REFERENCES ESPECIE(CODIGO);

ALTER TABLE ESPECIE ADD CONSTRAINT FK1_ESPECIE FOREIGN KEY (CALADERO_PRINCIPAL) REFERENCES CALADERO(CODIGO);

ALTER TABLE FECHA_CAPTURAS_PERMITIDAS ADD CONSTRAINT PK_FECHA_CAPTURAS_PERMITIDAS PRIMARY KEY (COD_ESPECIE, COD_CALADERO);
ALTER TABLE FECHA_CAPTURAS_PERMITIDAS ADD CONSTRAINT FK1_FECHA_CAPTURAS_PERMITIDAS FOREIGN KEY (COD_ESPECIE) REFERENCES ESPECIE(CODIGO);
ALTER TABLE FECHA_CAPTURAS_PERMITIDAS ADD CONSTRAINT FK2_FECHA_CAPTURAS_PERMITIDAS FOREIGN KEY (COD_CALADERO) REFERENCES CALADERO(CODIGO);

ALTER TABLE FECHA_CAPTURAS_PERMITIDAS ADD CONSTRAINT CHK_FECHA_INICIALMES CHECK (NOT (((EXTRACT(MONTH FROM (FECHA_INICIAL))= 2) AND (EXTRACT (DAY FROM (FECHA_INICIAL)) IN (2,28))) OR (EXTRACT(MONTH FROM (FECHA_INICIAL)) = 3) AND (EXTRACT(DAY FROM (FECHA_INICIAL)) IN (1,28))));
ALTER TABLE FECHA_CAPTURAS_PERMITIDAS ADD CONSTRAINT CHK_FECHA_FINALMES CHECK (NOT (((EXTRACT(MONTH FROM (FECHA_FINAL)) = 2) AND (EXTRACT(DAY FROM (FECHA_FINAL)) IN (2,28))) OR (EXTRACT(MONTH FROM (FECHA_FINAL)) = 3) AND (EXTRACT(DAY FROM (FECHA_FINAL)) IN (1,28))));


ALTER TABLE LOTES ADD CONSTRAINT CHK_PECIORPRKILOADJUDICADO CHECK (PRECIOPORKILOADJUDICADO > PRECIOPORKILOSALIDA);
ALTER TABLE LOTES ADD CONSTRAINT CHK_NUMKILOS CHECK (PRECIOPORKILOADJUDICADO > PRECIOPORKILOSALIDA);
ALTER TABLE LOTES ADD CONSTRAINT CHK_LOTES CHECK (NUMKILOS > 0 AND PRECIOPORKILOADJUDICADO > 0 AND PRECIOPORKILOSALIDA > 0);
ALTER TABLE CALADERO ADD CONSTRAINT CHK_CALADERO CHECK (NOMBRE = UPPER(NOMBRE) AND UBICACION = UPPER(UBICACION));

INSERT INTO BARCOS VALUES ('AA-1113','1','1','1',1,'1');
INSERT INTO ESPECIE VALUES ('1', '1', '1', 10, NULL);
INSERT INTO LOTES VALUES ('1', 'AA-1113', 1,1,2, '2025-04-04','1');
INSERT INTO CALADERO VALUES ('1', '1', '1', '1');
INSERT INTO FECHA_CAPTURAS_PERMITIDAS VALUES('1','1','2025-02-01','2025-03-29');

SELECT * FROM BARCOS;
SELECT * FROM ESPECIE;
SELECT * FROM LOTES;
SELECT * FROM CALADERO;
SELECT * FROM FECHA_CAPTURAS_PERMITIDAS;