CREATE TABLE REGION
(
	CODREGION NUMBER(20),
	NOMBRE VARCHAR2(25),
	CONSTRAINT PK_REGION PRIMARY KEY (CODREGION)
);

CREATE TABLE PROVINCIA
(
	CODPROVINCIA NUMBER(20),
	NOMBRE VARCHAR2(25),
	CODREGION NUMBER(20),
	CONSTRAINT PK_PROVINCIA PRIMARY KEY (CODPROVINCIA),
	CONSTRAINT FK1_PROVINCIA FOREIGN KEY (CODREGION) REFERENCES REGION(CODREGION)
);

CREATE TABLE LOCALIDAD
(
	CODLOCALIDAD NUMBER(20),
	NOMBRE VARCHAR2(25),
	CODPROVINCIA NUMBER(20),
	CONSTRAINT PK_LOCALIDAD PRIMARY KEY (CODLOCALIDAD),
	CONSTRAINT FK1_LOCALIDAD FOREIGN KEY (CODPROVINCIA) REFERENCES PROVINCIA(CODPROVINCIA)
);

CREATE TABLE EMPLEADO
(
	ID NUMBER(20),
	DNI VARCHAR2(10) UNIQUE,
	NOMBRE VARCHAR2(25),
	FECHANAC DATE,
	TELEFONO NUMBER(10),
	SALARIO NUMBER(10,2),
	CODLOCALIDAD NUMBER(20),
	CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID),
	CONSTRAINT FK1_EMPLEADO FOREIGN KEY (CODLOCALIDAD) REFERENCES LOCALIDAD(CODLOCALIDAD)
);
