CREATE TABLE ALUMNO
(
	NUMMATRICULA NUMBER(20),
	NOMBRE VARCHAR2(25),
	FECHANACIMIENTO DATE,
	TELEFONO NUMBER(10),
	CONSTRAINT PK_ALUMNO PRIMARY KEY (NUMMATRICULA)
);

CREATE TABLE PROFESOR
(
	IDPROFESOR VARCHAR2(20),
	NIF_P VARCHAR2(10) UNIQUE,
	NOMBRE VARCHAR2(25),
	ESPECIALIDAD VARCHAR2(50),
	TELEFONO NUMBER(10),
	CONSTRAINT PK_PROFESOR PRIMARY KEY (IDPROFESOR)
);

CREATE TABLE ASIGNATURA
(
	CODASIGNATURA VARCHAR2(20),
	NOMBRE VARCHAR2(25),
	IDPROFESOR VARCHAR2(20),
	CONSTRAINT PK_ASIGNATURA PRIMARY KEY (CODASIGNATURA),
	CONSTRAINT FK1_ASIGNATURA FOREIGN KEY (IDPROFESOR) REFERENCES PROFESOR(IDPROFESOR)
);

CREATE TABLE RECIBE
(
	NUMMATRICULA NUMBER(20),
	CODASIGNATURA VARCHAR2(20),
	CURSOESCOLAR VARCHAR2(10),
	CONSTRAINT PK_RECIBE PRIMARY KEY (NUMMATRICULA, CODASIGNATURA, CURSOESCOLAR),
	CONSTRAINT FK1_RECIBE FOREIGN KEY (NUMMATRICULA) REFERENCES ALUMNO(NUMMATRICULA),
	CONSTRAINT FK2_RECIBE FOREIGN KEY (CODASIGNATURA) REFERENCES ASIGNATURA(CODASIGNATURA)
);
