CREATE TABLE CLIENTE
(
	NUMCLIENTE NUMBER(10),
	SALDO NUMBER(10,2),
	LIMCREDRITO NUMBER (10,2),
	DESCUENTO NUMBER (10,2)
);
CREATE TABLE DIRECCION
(
	CODDIRECCION VARCHAR2(10),
	VIA VARCHAR2(50),
	NUMERO NUMBER(5),
	PISO VARCHAR2(10),
	PORTAL VARCHAR2(5),
	CODPOSTAL NUMBER(10)
);
CREATE TABLE POSEE
(
	NUMCLIENTE NUMBER(10),
	CODDIRECCION VARCHAR2(10)
);
CREATE TABLE PEDIDO
(
	NUMPEDIDO NUMBER(10),
	FECHA DATE,
	NUMCLIENTE NUMBER(10),
	CODDIRECCION VARCHAR2(10)
);
CREATE TABLE FABRICA
(
	NUMFABRICA NUMBER(10),
	TELEFONO NUMBER(10)
);
CREATE TABLE ARTICULO
(
	NUMARTICULO NUMBER(10),
	DESCRIPCION VARCHAR2(1000)
);
CREATE TABLE DISTRIBUYE
(
	NUMARTICULO NUMBER(10),
	NUMFABRICA NUMBER(10),
	CANTSUMINISTRO NUMBER(10),
	EXISTENCIAS NUMBER(10)
);
CREATE TABLE INCLUYE
(
	NUMPEDIDO NUMBER(10),
	NUMARTICULO NUMBER(10),
	CANTIDAD NUMBER(10)
);

-- TABLA CLIENTE
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (NUMCLIENTE);
CREATE SEQUENCE AUTO_NUMCLIENTE START WITH 1 INCREMENT BY 1 MAXVALUE 999999999;

-- TABLA CLIENTE
ALTER TABLE DIRECCION ADD CONSTRAINT PK_DIRECCION PRIMARY KEY (CODDIRECCION);

-- TABLA POSEE
ALTER TABLE POSEE ADD CONSTRAINT PK_POSEE PRIMARY KEY (NUMCLIENTE, CODDIRECCION);
ALTER TABLE POSEE ADD CONSTRAINT FK1_POSEE FOREIGN KEY (NUMCLIENTE) REFERENCES CLIENTE(NUMCLIENTE);
ALTER TABLE POSEE ADD CONSTRAINT FK2_POSEE FOREIGN KEY (CODDIRECCION) REFERENCES DIRECCION(CODDIRECCION);

-- TABLA PEDIDO
ALTER TABLE PEDIDO ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMPEDIDO);
ALTER TABLE PEDIDO ADD CONSTRAINT FK1_PEDIDO FOREIGN KEY (NUMCLIENTE) REFERENCES CLIENTE(NUMCLIENTE);
ALTER TABLE PEDIDO ADD CONSTRAINT FK2_PEDIDO FOREIGN KEY (CODDIRECCION) REFERENCES DIRECCION(CODDIRECCION);

-- TABLA FABRICA
ALTER TABLE FABRICA ADD CONSTRAINT PK_FABRICA PRIMARY KEY (NUMFABRICA);
CREATE SEQUENCE AUTO_NUMFABRICA START WITH 1 INCREMENT BY 1 MAXVALUE 999999999;

-- TABLA ARTICULO
ALTER TABLE ARTICULO ADD CONSTRAINT PK_ARTICULO PRIMARY KEY (NUMARTICULO);
CREATE SEQUENCE AUTO_NUMARTICULO START WITH 1 INCREMENT BY 1 MAXVALUE 999999999;

-- TABLA DISTRIBUYE
ALTER TABLE DISTRIBUYE ADD CONSTRAINT PK_DISTRIBUYE PRIMARY KEY (NUMARTICULO, NUMFABRICA);
ALTER TABLE DISTRIBUYE ADD CONSTRAINT FK1_DISTRIBUYE FOREIGN KEY (NUMARTICULO) REFERENCES ARTICULO(NUMARTICULO);
ALTER TABLE DISTRIBUYE ADD CONSTRAINT FK2_DISTRIBUYE FOREIGN KEY (NUMFABRICA) REFERENCES FABRICA(NUMFABRICA);

--TABLA INCLUYE
ALTER TABLE INCLUYE ADD CONSTRAINT PK_INCLUYE PRIMARY KEY (NUMPEDIDO, NUMARTICULO);
ALTER TABLE INCLUYE ADD CONSTRAINT FK1_INCLUYE FOREIGN KEY (NUMPEDIDO) REFERENCES PEDIDO(NUMPEDIDO);
ALTER TABLE INCLUYE ADD CONSTRAINT FK2_INCLUYE FOREIGN KEY (NUMARTICULO) REFERENCES ARTICULO(NUMARTICULO);

INSERT INTO CLIENTE VALUES (AUTO_NUMCLIENTE.NEXTVAL, '11', '10.1', '10');
SELECT * FROM CLIENTE;

INSERT INTO FABRICA VALUES (AUTO_NUMFABRICA.NEXTVAL, '2');
SELECT * FROM FABRICA;

INSERT INTO ARTICULO VALUES (AUTO_NUMARTICULO.NEXTVAL, 'HOLA');
SELECT * FROM ARTICULO;
