CREATE TABLE CURSO
(
	CODCURSO VARCHAR2(10),
	NOMBRE VARCHAR2(50),
	DURACION VARCHAR2(20),
	COSTE NUMBER(10,2)
);
CREATE TABLE PRERREQUISITO
(
	CURSOSOLICITADO VARCHAR2(10),
	CURSOPREVIO VARCHAR2(10),
	OBLIGATORIO VARCHAR2(5)
);
CREATE TABLE EMPLEADO
(
	CODEMP VARCHAR2(10),
	NIF	VARCHAR2(10) UNIQUE,
	NOMBRE VARCHAR2(20),
	APELLIDOS VARCHAR2(40),
	DIRECCION VARCHAR2(50),
	TELEFONO NUMBER(10),
	FECHANAC DATE,
	SALARIO NUMBER(10,2)
);
CREATE TABLE EMPNOCAPACITADO
(
	CODEMP VARCHAR2(10)
);
CREATE TABLE EMPCAPACITADO
(
	CODEMP VARCHAR2 (10)
);
CREATE TABLE EDICION
(
	CODCURSO VARCHAR2(10),
	FECHAINICIO DATE,
	LUGAR VARCHAR2(50),
	HORARIO VARCHAR2(30),
	PROFESOR VARCHAR2(10)
);
CREATE TABLE RECIBE
(
	CODEMPLEADO VARCHAR2(10),
	CODCURSO VARCHAR2(10),
	FECHAINICIO DATE
);

-- CURSO
ALTER TABLE CURSO ADD CONSTRAINT PK_CURSO PRIMARY KEY (CODCURSO);

-- PRERREQUISITO
ALTER TABLE PRERREQUISITO ADD CONSTRAINT PK_PRERREQUISITO PRIMARY KEY (CURSOSOLICITADO, CURSOPREVIO); 
ALTER TABLE PRERREQUISITO ADD CONSTRAINT FK1_PRERREQUISITO FOREIGN KEY (CURSOSOLICITADO) REFERENCES CURSO(CODCURSO); 
ALTER TABLE PRERREQUISITO ADD CONSTRAINT FK2_PRERREQUISITO FOREIGN KEY (CURSOPREVIO) REFERENCES CURSO(CODCURSO); 
ALTER TABLE PRERREQUISITO ADD CONSTRAINT CHK_PRERREQUISITO CHECK (OBLIGATORIO IN ('SI', 'NO')); 

-- EMPLEADO
ALTER TABLE EMPLEADO ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY (CODEMP);

-- EMPNOCAPACITADO
ALTER TABLE EMPNOCAPACITADO ADD CONSTRAINT PK_EMPNOCAPACITADO PRIMARY KEY (CODEMP);
ALTER TABLE EMPNOCAPACITADO ADD CONSTRAINT FK1_EMPNOCAPACITADO FOREIGN KEY (CODEMP) REFERENCES EMPLEADO(CODEMP); 

-- EMPCAPACITADO
ALTER TABLE EMPCAPACITADO ADD CONSTRAINT PK_EMPCAPACITADO PRIMARY KEY (CODEMP);
ALTER TABLE EMPCAPACITADO ADD CONSTRAINT FK1_EMPCAPACITADO FOREIGN KEY (CODEMP) REFERENCES EMPLEADO(CODEMP); 

-- EDICION
ALTER TABLE EDICION ADD CONSTRAINT PK_EDICION PRIMARY KEY (CODCURSO, FECHAINICIO);
ALTER TABLE EDICION ADD CONSTRAINT FK1_EDICION FOREIGN KEY (CODCURSO) REFERENCES CURSO(CODCURSO);
ALTER TABLE EDICION ADD CONSTRAINT FK2_EDICION FOREIGN KEY (PROFESOR) REFERENCES EMPCAPACITADO(CODEMP);

-- RECIBE
ALTER TABLE RECIBE ADD CONSTRAINT PK_RECIBE PRIMARY KEY (CODEMPLEADO, CODCURSO, FECHAINICIO);
ALTER TABLE RECIBE ADD CONSTRAINT FK1_RECIBE FOREIGN KEY (CODEMPLEADO) REFERENCES EMPLEADO(CODEMP);
ALTER TABLE RECIBE ADD CONSTRAINT FK2_RECIBE FOREIGN KEY (CODCURSO, FECHAINICIO) REFERENCES EDICION(CODCURSO, FECHAINICIO);
