CREATE TABLE PROFESORES
(
	NOMBRE VARCHAR2(20),
	APELLIDO1 VARCHAR2(20),
	APELLIDO2 VARCHAR2(20),
	DNI VARCHAR2(10),
	DIRECCION VARCHAR2(50),
	TITULO VARCHAR2(20),
	GANA NUMBER(10,2),
	CONSTRAINT PK_PROFESORES PRIMARY KEY (DNI)
);
CREATE TABLE CURSOS
(
	NOMBRE_CURSO VARCHAR2(50),
	COD_CURSO VARCHAR2(10),
	DNI_PROF VARCHAR2(10),
	MAX_ALU NUMBER(5),
	FECHA_INI DATE,
	FECHA_FIN DATE,
	NUM_HORAS NUMBER,
	CONSTRAINT PK_CURSOS PRIMARY KEY (COD_CURSO),
	CONSTRAINT FK1_CURSO FOREIGN KEY (DNI_PROF) REFERENCES PROFESORES(DNI) ON DELETE CASCADE
);
CREATE TABLE ALUMNOS
(
	NOMBRE VARCHAR2(20),
	APELLIDO1 VARCHAR2(20),
	APELLIDO2 VARCHAR2(20),
	DNI VARCHAR2(10),
	DIRECCION VARCHAR2(50),
	SEXO VARCHAR2(5),
	FECHA_NACIMIENTO DATE,
	CURSO VARCHAR2 (10),
	CONSTRAINT PK_ALUMNOS PRIMARY KEY (DNI),
	CONSTRAINT FK1_ALUMNOS FOREIGN KEY (CURSO) REFERENCES CURSOS(COD_CURSO) ON DELETE CASCADE,
	CONSTRAINT CHK_SEXO CHECK (SEXO IN ('H','M'))
);

INSERT INTO PROFESORES VALUES ('JUAN', 'ARCH', 'LOPEZ', '32432455','PUERTA NEGRA, 4','ING. INFORMÁTICA','7500');
INSERT INTO PROFESORES VALUES ('MARIA', 'OLIVA', 'RUBIO', '43215643','JUAN ALFONSO 32','LDA. FIL. INGLESA','5400');


INSERT INTO CURSOS VALUES ('INGLÉS BÁSICO','1','43215643', 15,TO_DATE('01/11/00' , 'DD/MM/YY'), TO_DATE('22-DIC-00' , 'DD-MM-YY'),120);
INSERT INTO CURSOS VALUES ('ADMINISTRACION LINUX','2','32432455', NULL,TO_DATE('01/SEP/00' , 'DD/MM/YY'), NULL,80);


INSERT INTO ALUMNOS VALUES('LUCAS','MANILVA','LOPEZ','123523','ALHAMAR,3','H',TO_DATE('01/11/79','DD/MM/YY'),'1');
INSERT INTO ALUMNOS VALUES('ANTONIA','LOPEZ','ALCANTARA','2567567','MANIQUI,21','M',NULL,'2');
INSERT INTO ALUMNOS VALUES('MANUEL','ALCANTARA','PEDRÓS','3123689','JULIAN, 2','H',NULL,'1');
INSERT INTO ALUMNOS VALUES('JOSÉ','PÉREZ','CABALLAR','4896765','JARCHA, 5','H',TO_DATE('03/02/77','DD/MM/YY'),'2');


-- 3
INSERT INTO ALUMNOS VALUES('SERGIO','NAVAS','RETAL','123522',NULL,'H',NULL,'1');

-- 4 
-- ESTA PERSONA YA ESTA EN LA TABLA LE HE CAMBIADO EL DNI PARA QUE NO DE ERROR AHORA Y EL NOMBRE PARA QUE NO DE ERROR EN EL EJERCICIO 14
INSERT INTO PROFESORES VALUES ('JUANA', 'ARCH', 'LOPEZ', '42432455','PUERTA NEGRA, 4','ING. INFORMATICA',NULL);

-- 5
INSERT INTO ALUMNOS VALUES('MARIA','JAEN','SEVILLA','789678','MARTOS, 5','M',NULL,NULL);

-- 6
UPDATE ALUMNOS
SET FECHA_NACIMIENTO = TO_DATE('23/12/76', 'DD/MM/YY')
WHERE DNI = '2567567';

-- 7
UPDATE ALUMNOS
SET CURSO = 1
WHERE NOMBRE = 'ANTONIA' AND APELLIDO1 = 'LOPEZ';

--8
DELETE FROM PROFESORES
WHERE NOMBRE = 'LAURA' AND APELLIDO1 = 'JIMÉNEZ';

-- 9
DELETE FROM CURSOS
WHERE COD_CURSO = '1';

-- 10
ALTER TABLE CURSOS
ADD numero_alumnos NUMBER(10);

-- 11
UPDATE ALUMNOS
SET FECHA_NACIMIENTO = TO_DATE('2012/01/01','YYYY/MM/DD')
WHERE FECHA_NACIMIENTO = NULL;

-- 12
ALTER TABLE ALUMNOS
DROP COLUMN SEXO;

-- 13
UPDATE PROFESORES
SET GANA = GANA * 1.20
WHERE TITULO = 'ING. INFORMÁTICA';

-- 14
UPDATE CURSOS
SET DNI_PROF = '1234567'
WHERE DNI_PROF = '32432455';

UPDATE PROFESORES
SET DNI = '1234567'
WHERE NOMBRE = 'JUAN' AND APELLIDO1 = 'ARCH';


-- 15
UPDATE PROFESORES
SET DNI = '7654321'
WHERE TITULO = 'ING. INFORMÁTICA';

-- 16
UPDATE ALUMNOS
SET SEXO = 'M'
WHERE NOMBRE = 'MARIA' AND APELLIDO1 = 'JAEN';