-- 1 Y 6
SELECT aa.IDALUMNO  FROM ALUMNO_ASIGNATURA aa 
WHERE aa.IDASIGNATURA NOT IN ('150212' , '130113');

-- 2 y 8
SELECT a.NOMBRE FROM ASIGNATURA a
WHERE a.CREDITOS > (SELECT a2.CREDITOS FROM ASIGNATURA a2
					WHERE UPPER(a2.NOMBRE) LIKE 'SEGURIDAD VIAL');

-- 3
SELECT aa.IDALUMNO  FROM ALUMNO_ASIGNATURA aa 
WHERE aa.IDASIGNATURA IN ('150212' ,'130113')
GROUP BY aa.IDALUMNO 
HAVING COUNT(DISTINCT aa.IDASIGNATURA) = 2; 

-- 4
SELECT aa.IDALUMNO  FROM ALUMNO_ASIGNATURA aa 
WHERE aa.IDASIGNATURA IN ('150212' ,'130113')
GROUP BY aa.IDALUMNO 
HAVING COUNT(DISTINCT aa.IDASIGNATURA) = 1;

-- 5
SELECT A.NOMBRE FROM ASIGNATURA A
WHERE IDTITULACION = '130110'
AND COSTEBASICO > ( SELECT AVG(NVL(COSTEBASICO, 0))
					FROM ASIGNATURA
					WHERE IDTITULACION = '130110');

-- 7
SELECT AA.IDALUMNO
FROM ALUMNO_ASIGNATURA AA
WHERE AA.IDASIGNATURA = '150212'
AND AA.IDALUMNO NOT IN (SELECT AA2.IDALUMNO
						FROM ALUMNO_ASIGNATURA AA2
						WHERE AA2.IDASIGNATURA = '130113');

-- 9
SELECT * FROM PERSONA
WHERE DNI NOT IN (SELECT DNI FROM PROFESOR)
AND DNI NOT IN (SELECT DNI FROM ALUMNO);

-- 10
SELECT NOMBRE FROM ASIGNATURA
WHERE CREDITOS = ( SELECT MAX(CREDITOS)
					FROM ASIGNATURA);

-- 11
SELECT NOMBRE FROM ASIGNATURA
WHERE IDASIGNATURA NOT IN (SELECT IDASIGNATURA
							FROM ALUMNO_ASIGNATURA);

-- 12
SELECT DISTINCT P.CIUDAD FROM PERSONA P
WHERE EXISTS (SELECT * FROM PROFESOR PR
				WHERE PR.DNI = P.DNI)
AND EXISTS (SELECT * FROM ALUMNO AL
			WHERE AL.DNI = P.DNI);


SELECT p.CIUDAD  FROM PERSONA p
JOIN ALUMNO a 
ON p.DNI = a.DNI
JOIN PROFESOR p2 
ON p.DNI = p2.DNI;




