CREATE TABLE PROFESORES 
(
    DNI NUMBER(10),
    NOMBRE VARCHAR2(25),
    APELLIDO1 VARCHAR2(25),
    APELLIDO2 VARCHAR2(25),
    DIRECCION VARCHAR2(100),
    TITULO VARCHAR2(50),
    GANA NUMBER(10,2),
	CONSTRAINT PK_PROFESORES PRIMARY KEY (DNI)
);

CREATE TABLE CURSOS 
(
    COD_CURSO NUMBER(10),
    NOMBRE_CURSO VARCHAR2(50),
    DNI_PROFESOR NUMBER(10),
    MAXIMO_ALUMNOS NUMBER(10),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    NUM_HORAS NUMBER (10),
    CONSTRAINT PK_CURSOS PRIMARY KEY (COD_CURSO),
    CONSTRAINT FK_PROFESOR FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESORES(DNI)
);

CREATE TABLE ALUMNOS 
(
    DNI NUMBER(10),
    NOMBRE VARCHAR2(50),
    APELLIDO1 VARCHAR2(50),
    APELLIDO2 VARCHAR2(50),
    DIRECCION VARCHAR2(50),
    SEXO VARCHAR2(10),
    FECHA_NACIMIENTO DATE,
    CURSO NUMBER (10),
    CONSTRAINT PK_ALUMNOS PRIMARY KEY (DNI),
    CONSTRAINT FK_CURSO FOREIGN KEY (CURSO) REFERENCES CURSOS(COD_CURSO),
    CONSTRAINT CHK_SEXO CHECK (SEXO IN ('M','F'))
);

--2
INSERT INTO PROFESORES VALUES (32432455, 'JUAN', 'ARCH', 'LÓPEZ', 'PUERTA NEGRA, 4', 'ING. INFORMÁTICA', 7500);
INSERT INTO PROFESORES VALUES (43215643, 'MARÍA', 'OLIVA', 'RUBIO', 'JUAN ALFONSO 32', 'LDA. FIL. INGLESA', 5400);

INSERT INTO CURSOS VALUES (1, 'INGLÉS BÁSICO', 43215643, 15,TO_DATE('01/11/00','DD/MM/YY'),TO_DATE('22/12/00','DD/MM/YY'), 120);
INSERT INTO CURSOS VALUES (2, 'ADMINISTRACIÓN LINUX', 32432455, NULL, TO_DATE('01/09/00','DD/MM/YY'), NULL, 80);

INSERT INTO ALUMNOS VALUES(123523, 'LUCAS', 'MANILVA', 'LÓPEZ', 'ALHAMAR, 3', 'M',TO_DATE('01/11/79','DD/MM/YY'), 1);
INSERT INTO ALUMNOS VALUES(2567567, 'ANTONIA', 'LÓPEZ', 'ALCANTARA', 'MANIQUÍ, 21', 'F', NULL, 2);
INSERT INTO ALUMNOS VALUES(3123689, 'MANUEL', 'ALCÁNTARA', 'PEDRÓS', 'JULIAN, 2', 'M', NULL, 1);

INSERT INTO CURSOS (COD_CURSO, NOMBRE_CURSO) VALUES (3, 'INGLÉS INTERMEDIO');
INSERT INTO ALUMNOS VALUES(4896765, 'JOSÉ', 'PÉREZ', 'CABALLAR', 'JARCHE, 5', 'M',TO_DATE('03/02/77','DD/MM/YY'), 3);

--3
INSERT INTO ALUMNOS (DNI, NOMBRE, APELLIDO1, APELLIDO2, SEXO, CURSO) VALUES (123522, 'SERGIO', 'NAVAS', 'RETAL', 'M', 1);

--4
INSERT INTO PROFESORES VALUES (32432454, 'JUANA', 'ARCH', 'LÓPEZ', 'PUERTA NEGRA, 4','ING. INFORMÁTICA', NULL);

--5
INSERT INTO ALUMNOS(DNI, NOMBRE, APELLIDO1, APELLIDO2, DIRECCION, SEXO) VALUES (789678, 'MARÍA', 'JAÉN', 'SEVILLA', 'MARTOS, 5', 'M');

--6
UPDATE ALUMNOS SET FECHA_NACIMIENTO = TO_DATE('23/12/1976','DD/MM/YYYY') WHERE NOMBRE = 'ANTONIA' AND APELLIDO1 = 'LÓPEZ';

--7 HE CREADO EL CURSO CON CODIGO 5
INSERT INTO CURSOS (COD_CURSO, NOMBRE_CURSO) VALUES (5,'INGLES AVANZADO');
UPDATE ALUMNOS SET CURSO = 5 WHERE NOMBRE = 'ANTONIA' AND APELLIDO1 = 'LÓPEZ';

--8
DELETE FROM PROFESORES WHERE NOMBRE = 'LAURA' AND APELLIDO1 = 'JIMÉNEZ';

--9 AL TENER HIJOS PRIMERO HABRIA QUE DEJAR LOS VALORES DE ESOS HIJOS EN NULL
UPDATE ALUMNOS SET CURSO = NULL WHERE CURSO = 1;
DELETE FROM CURSOS WHERE COD_CURSO = 1;

--10
ALTER TABLE CURSOS ADD NUMERO_ALUMNOS NUMBER(10);

--11
UPDATE ALUMNOS SET FECHA_NACIMIENTO = TO_DATE('01/01/2012','DD/MM/YYYY') WHERE FECHA_NACIMIENTO IS NULL;

--12
ALTER TABLE ALUMNOS DROP COLUMN SEXO;

--13
UPDATE PROFESORES SET GANA = GANA * 1.20 WHERE TITULO LIKE '%INFORMÁTICA%';

--14
UPDATE PROFESORES SET DNI = 2234567 WHERE NOMBRE = 'JUANI' AND APELLIDO1 = 'ARCH';

--15 ESTE DARIA ERROR PORQUE HAY 2 PERSONAS CON ESE TITULO POR LO QUE LA PK DARIA ERROR
--  UPDATE PROFESORES SET DNI = 7654321 WHERE TITULO LIKE '%INFORMÁTICA%';

--16 ESTE DARIA ERROR PORQUE HE BORRADO ANTERIORMENTE ESA COLUMNA
-- UPDATE ALUMNOS SET SEXO = 'F' WHERE NOMBRE = 'MARÍA' AND APELLIDO1 = 'JAÉN';
