CREATE TABLE DIRECTOR(
	NOMBRE VARCHAR2 (25),
	NACIONALIDAD VARCHAR2(15),
	CONSTRAINT PK_DIRECTOR PRIMARY KEY (NOMBRE)
);
CREATE TABLE PELICULA(
	ID VARCHAR2 (15),
	TITULO VARCHAR2(25) NOT NULL,
	PRODUCTORA VARCHAR2(25),
	NACIONALIDAD VARCHAR2(25),
	FECHA DATE,
	DIRECTOR VARCHAR2(25),
	CONSTRAINT PK_PELICULA PRIMARY KEY (ID),
	CONSTRAINT FK1_PELICULA FOREIGN KEY (DIRECTOR) REFERENCES DIRECTOR(NOMBRE)
);
CREATE TABLE ACTORES(
	NOMBRE VARCHAR2(25),
	NACIONALIDAD VARCHAR2(25),
	SEXO VARCHAR2(10),
	CONSTRAINT PK_ACTORES PRIMARY KEY (NOMBRE),
	CONSTRAINT CHK_ACTORES CHECK (SEXO IN ('H', 'M'))
);
CREATE TABLE ACTUA(
	ACTOR VARCHAR2(25),
	ID_PELI VARCHAR2 (15),
	PROTA VARCHAR2 (2) DEFAULT 'NO',
	CONSTRAINT PK_ACTUA PRIMARY KEY (ACTOR, ID_PELI),
	CONSTRAINT FK1_ACTUA FOREIGN KEY (ACTOR) REFERENCES ACTORES(NOMBRE),
	CONSTRAINT FK2_ACTUA FOREIGN KEY (ID_PELI) REFERENCES PELICULA(ID),
	CONSTRAINT CHK_ACTUA CHECK (PROTA IN('NO','SI'))
);
CREATE TABLE EJEMPLAR(
	ID_PELI VARCHAR2 (15),
	NUMERO NUMBER(10),
	ESTADO VARCHAR2(10),
	CONSTRAINT PK_EJEMPLAR PRIMARY KEY (ID_PELI, NUMERO),
	CONSTRAINT FK_EJEMPLAR FOREIGN KEY (ID_PELI) REFERENCES PELICULA(ID)
);
CREATE TABLE SOCIO(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(25) NOT NULL,
	DIRECCION VARCHAR2(50),
	TELEFONO NUMBER(10),
	AVALADOR VARCHAR2(10),
	CONSTRAINT PK_SOCIO PRIMARY KEY (DNI),
	CONSTRAINT FK1_SOCIO FOREIGN KEY (AVALADOR) REFERENCES SOCIO(DNI)
);
CREATE TABLE ALQUILA(
	DNI VARCHAR2(10),
	ID_PELI VARCHAR2 (15),
	NUMERO NUMBER(10),
	FECHAALQUILER DATE,
	FECHADEVOLUCION DATE,
	CONSTRAINT PK_ALQUILA PRIMARY KEY (DNI, ID_PELI, NUMERO, FECHAALQUILER),
	CONSTRAINT FK1_ALQUILA FOREIGN KEY (DNI) REFERENCES SOCIO(DNI),
	CONSTRAINT FK2_ALQUILA FOREIGN KEY (ID_PELI, NUMERO) REFERENCES EJEMPLAR(ID_PELI, NUMERO)
);