CREATE TABLE SUCURSAL(
	CODIGO VARCHAR2 (25),
	DIRECCION VARCHAR2 (50),
	TELEFONO NUMBER (10),
	CONSTRAINT PK_SUCURSAL PRIMARY KEY (CODIGO)
);
CREATE TABLE EMPLEADO(
	DNI VARCHAR2 (10),
	NOMBRE VARCHAR2 (25) NOT NULL,
	DIRECCION VARCHAR2 (50),
	TELEFONO NUMBER (10),
	SUCURSAL VARCHAR2 (25),
	CONSTRAINT PK_EMPLEADO PRIMARY KEY (DNI),
	CONSTRAINT FK1_EMPLEADO FOREIGN KEY (SUCURSAL) REFERENCES SUCURSAL(CODIGO)
);
CREATE TABLE REVISTA(
	NUMREG NUMBER (10),
	TITULO VARCHAR2 (50) NOT NULL,
	PERIODICIDAD VARCHAR2 (20) DEFAULT 'MENSUAL',
	TIPO VARCHAR2(25),
	SUCURSAL VARCHAR2(25),
	CONSTRAINT PK_REVISTA PRIMARY KEY (NUMREG),
	CONSTRAINT FK1_REVISTA FOREIGN KEY (SUCURSAL) REFERENCES SUCURSAL (CODIGO),
	CONSTRAINT CHK_REVISTA CHECK (PERIODICIDAD IN ('SEMANAL','QUINCENAL','MENSUAL','TRIMESTRA','ANUAL'))
);

CREATE TABLE PERIODISTA(
	DNI VARCHAR2 (10),
	NOMBRE VARCHAR2 (25) NOT NULL,
	DIRECCION VARCHAR2 (50),
	TELEFONDO NUMBER(10),
	ESPECIALISTA VARCHAR2(20),
	CONSTRAINT PK_PERIODISTA PRIMARY KEY (DNI)
);
CREATE TABLE ESCRIBE(
	NUMREG NUMBER (10),
	DNI_PER VARCHAR(10),
	CONSTRAINT PK_ESCRIBE PRIMARY KEY (NUMREG, DNI_PER),
	CONSTRAINT FK1_ESCRIBE FOREIGN KEY (NUMREG) REFERENCES REVISTA (NUMREG),
	CONSTRAINT FK2_ESCRIBE FOREIGN KEY (DNI_PER) REFERENCES PERIODISTA (DNI)
);
CREATE TABLE NUMREVISTA(
	NUMREG NUMBER (10),
	NUMERO NUMBER (10),
	NUMPAGINAS NUMBER (10) DEFAULT '1',
	FECHA DATE,
	CANTVENDIDAS NUMBER(10),
	CONSTRAINT PK_NUMREVISTA PRIMARY KEY (NUMREG, NUMERO),
	CONSTRAINT FK1_NUMREVISTA FOREIGN KEY (NUMREG) REFERENCES REVISTA (NUMREG)
);
