CREATE TABLE CLIENTE(
	NIF VARCHAR2(10),
	NOMBRE VARCHAR2(25),
	DIRECCION VARCHAR2(50),
	TELEFONO NUMBER(10),
	CONSTRAINT PK1_CLIENTE PRIMARY KEY (NIF)
);

CREATE TABLE MODELODORMITORIO(
	COD VARCHAR2(25),
	CONSTRAINT PK1_MODELODORMITORIO PRIMARY KEY (COD)
);

CREATE TABLE COMPRA(
	NIF_C VARCHAR2(25),
	MODELO VARCHAR2(25),
	FECHACOMPRA DATE,
	CONSTRAINT PK_COMPRA PRIMARY KEY (NIF_C, MODELO, FECHACOMPRA),
	CONSTRAINT FK1_COMPRA FOREIGN KEY (NIF_C) REFERENCES CLIENTE (NIF),
	CONSTRAINT FK2_COMPRA FOREIGN KEY (MODELO) REFERENCES MODELODORMITORIO (COD)
);

CREATE TABLE MONTADOR(
	NIF VARCHAR2 (10),
	NOMBRE VARCHAR2 (25),
	DIRECCION VARCHAR2(50),
	TELEFONO NUMBER(10),
	CONSTRAINT PK_MONTADOR PRIMARY KEY (NIF)
);

CREATE TABLE MONTA(
	MODELO VARCHAR2(25),
	NIF_M VARCHAR2(10),
	FECHAMONTAJE DATE,
	CONSTRAINT PK_MONTA PRIMARY KEY (MODELO, NIF_M, FECHAMONTAJE),
	CONSTRAINT FK1_MONTA FOREIGN KEY (MODELO) REFERENCES MODELODORMITORIO (COD),
	CONSTRAINT FK2_MONTA FOREIGN KEY (NIF_M) REFERENCES MONTADOR (NIF)
);