CREATE TABLE TELEFONO
(
	NUMERO NUMBER (10)
);
CREATE TABLE CLIENTE
(
	CODCLIENTE VARCHAR2(20),
	NOMBRE VARCHAR2(25),
	CALLE VARCHAR2(50),
	NUMERO NUMBER(10),
	COMUNA NUMBER(10),
	CIUDAD VARCHAR2(50)
);
CREATE TABLE ASOCIADO
(
	CODCLIENTE VARCHAR2(20),
	NUMTELEFONO NUMBER(10)
);
CREATE TABLE VENTA
(
	IDVENTA VARCHAR2(20),
	MONTOTOTAL NUMBER(10),
	CODCLIENTE VARCHAR2(20)
);
CREATE TABLE CATEGORIA
(
	IDCATEGORIA VARCHAR2(10),
	NOMBRE VARCHAR2(25),
	DESCRIPCION VARCHAR2(2000)
);
CREATE TABLE PROVEEDOR
(
	CODPROVEEDOR VARCHAR2(10),
	NOMBRE VARCHAR2(25),
	DIRECCION VARCHAR2(50),
	TELEFONO NUMBER(10),
	WEB VARCHAR2(100)
);
CREATE TABLE PRODUCTO
(
	IDPRODUCTO VARCHAR2(10),
	NOMBRE VARCHAR2(25),
	PRECIO NUMBER(10,2),
	STOCK NUMBER(10),
	IDCATEGORIA VARCHAR2(10),
	IDPROVEEDOR VARCHAR2(10)
);
CREATE TABLE INCLUYE
(
	IDVENTA VARCHAR2(10),
	IDPRODUCTO VARCHAR2(10),
	CANTIDAD NUMBER(10),
	PRECIOVENTA NUMBER(10,2)
);

-- TELEFONO
ALTER TABLE TELEFONO ADD CONSTRAINT PK_TELEFONO PRIMARY KEY (NUMERO);

-- CLIENTE
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CODCLIENTE);

-- ASOCIADO
ALTER TABLE ASOCIADO ADD CONSTRAINT PK_ASOCIADO PRIMARY KEY (CODCLIENTE, NUMTELEFONO);
ALTER TABLE ASOCIADO ADD CONSTRAINT FK1_ASOCIADO FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE(CODCLIENTE);
ALTER TABLE ASOCIADO ADD CONSTRAINT FK2_ASOCIADO FOREIGN KEY (NUMTELEFONO) REFERENCES TELEFONO(NUMERO);

--VENTA
ALTER TABLE VENTA ADD CONSTRAINT PK_VENTA PRIMARY KEY (IDVENTA);
ALTER TABLE VENTA ADD CONSTRAINT FK1_VENTA FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE(CODCLIENTE);

--CATEGORIA
ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (IDCATEGORIA);

-- PROVEEDOR
ALTER TABLE PROVEEDOR ADD CONSTRAINT PK_PROVEEDOR PRIMARY KEY (CODPROVEEDOR);

-- PRODUCTO
ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY (IDPRODUCTO);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK1_PRODUCTO FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK2_PRODUCTO FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR(CODPROVEEDOR);

-- INCLUYE
ALTER TABLE INCLUYE ADD CONSTRAINT PK_INCLUYE PRIMARY KEY (IDVENTA, IDPRODUCTO);
ALTER TABLE INCLUYE ADD CONSTRAINT FK1_INCLUYE FOREIGN KEY (IDVENTA) REFERENCES VENTA(IDVENTA);
ALTER TABLE INCLUYE ADD CONSTRAINT FK2_INCLUYE FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO);