CREATE TABLE SUCURSAL
(
	CODSUCURSAL VARCHAR2(10),
	NOBRE VARCHAR2 (25),
	DIRECCION VARCHAR2(50),
	LOCALIDAD VARCHAR2(100)
);

CREATE TABLE CUENTA
(
	CODSUCURSAL VARCHAR2(10),
	CODCUENTA VARCHAR2(10)
);
CREATE TABLE TRANSACCION
(
	CODSUCURSAL VARCHAR2(10),
	CODCUENTA VARCHAR2(10),
	NUMTRANSACCION NUMBER(10),
	FECHA DATE,
	CANTIDAD NUMBER(10,2),
	TIPO VARCHAR2 (10)
);
CREATE TABLE CLIENTE
(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(25),
	DIRECCION VARCHAR2(50),
	LOCALIDAD VARCHAR2(50),
	FECHANAC DATE,
	SEXO VARCHAR2(10)
);

CREATE TABLE CLI_CUENTA
(
	CODSUCURSAL VARCHAR2(10),
	CODCUENTA VARCHAR2(10),
	DNI VARCHAR2(10)
);

--TABLA SUCURSAL
ALTER TABLE SUCURSAL ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY (CODSUCURSAL);
CREATE SEQUENCE SEC_SUCURSAL START WITH 101 INCREMENT BY 1 MAXVALUE 99999999;

--TABLA CUENTA
ALTER TABLE CUENTA ADD CONSTRAINT PK_CUENTA PRIMARY KEY (CODSUCURSAL, CODCUENTA);
ALTER TABLE CUENTA ADD CONSTRAINT FK1_CUENTA FOREIGN KEY (CODSUCURSAL) REFERENCES SUCURSAL(CODSUCURSAL);

--TABLA TRANSACCION
ALTER TABLE TRANSACCION ADD CONSTRAINT PK_TRANSACCION PRIMARY KEY (CODSUCURSAL, CODCUENTA, NUMTRANSACCION);
ALTER TABLE TRANSACCION ADD CONSTRAINT FK1_TRANSACCION FOREIGN KEY (CODSUCURSAL, CODCUENTA) REFERENCES CUENTA (CODSUCURSAL, CODCUENTA); 

--TABLA CLIENTE
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI);

--TABLA CLI_CUENTA
ALTER TABLE CLI_CUENTA ADD CONSTRAINT PK_CLI_CUENTA PRIMARY KEY (CODSUCURSAL, CODCUENTA, DNI);
ALTER TABLE CLI_CUENTA ADD CONSTRAINT FK1_CLI_CUENTA FOREIGN KEY (CODSUCURSAL, CODCUENTA) REFERENCES CUENTA(CODSUCURSAL, CODCUENTA);
ALTER TABLE CLI_CUENTA ADD CONSTRAINT FK2_CLI_CUENTA FOREIGN KEY (DNI) REFERENCES CLIENTE(DNI);


INSERT INTO SUCURSAL VALUES (SEC_SUCURSAL.NEXTVAL, 'ALVARO2', 'LORA DEL RIO', 'SEVILLA');
SELECT * FROM SUCURSAL;