CREATE TABLE AUDITORIA_EMPLEADOS (descripcion VARCHAR2(200));

-- 1
CREATE OR REPLACE TRIGGER TRG_EMPLEADOS
AFTER INSERT OR DELETE ON EMPLEADOS
FOR EACH ROW
BEGIN
	IF INSERTING THEN
		INSERT INTO AUDITORIA_EMPLEADOS VALUES (TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') || 
										' usuario: '|| :NEW.NUMEM || ', ' || :NEW.NOMEM );
	ELSIF DELETING THEN
				INSERT INTO AUDITORIA_EMPLEADOS VALUES (TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') || 
										'el usuario: ' || :OLD.NUMEM || ', ' || :OLD.NOMEM);
	END IF;
END;


-- 2
CREATE OR REPLACE TRIGGER TRG_EMPLEADOS
AFTER UPDATE ON EMPLEADOS
FOR EACH ROW

BEGIN
	
		INSERT INTO AUDITORIA_EMPLEADOS VALUES ('tabla EMPLEADOS, fecha ' || TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ||
		
												' Ant NUMEN: ' || :OLD.NUMEM || ' New NUMEM: ' || :NEW.NUMEM ||
												' Ant FECNA: ' || :OLD.FECNA || ' New FECNA: ' || :NEW.FECNA ||
												' Ant NOMEM: ' || :OLD.NOMEM || ' New NOMEM: ' || :NEW.NOMEM ||
												' operacion: UPDATE');
END;

-- 3
CREATE OR REPLACE TRIGGER TRG_EMPLEADOS
AFTER UPDATE OF SALAR ON EMPLEADOS
FOR EACH ROW
WHEN (OLD.SALAR * 1.05 < NEW.SALAR)
BEGIN
	INSERT INTO AUDITORIA_EMPLEADOS VALUES (TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') || 
										' usuario: '|| :OLD.NUMEM || ', con salario anterior: ' 
										|| :OLD.SALAR || ', tiene actualmente un salario de: ' || :NEW.SALAR );
END;





INSERT INTO EMPLEADOS VALUES(1,1,SYSDATE,SYSDATE,NULL,NULL,NULL,'Javier',112); 
INSERT INTO EMPLEADOS VALUES(2,2,'06/09/1968','10/01/1988',1900,110,0,'Daniel',112); 

INSERT INTO (DNI, DEPARTAMENTO, JEFE) VALUES('47429121Q', 110, '47429121A');
INSERT INTO (DNI, DEPARTAMENTO, JEFE) VALUES('47429121A', 111, '47429121Q');
INSERT INTO (DNI, DEPARTAMENTO, JEFE) VALUES('47429121B', 111, '47429121Q');
INSERT INTO (DNI, DEPARTAMENTO, JEFE) VALUES('47429121C', 111, '47429121Q');
INSERT INTO (DNI, DEPARTAMENTO, JEFE) VALUES('47429121D', 110, '47429121Q');

UPDATE EMPLEADOS SET SALAR = 6000 WHERE NUMEM = 2;

SELECT * FROM EMPLEADOS;
SELECT * FROM DEPARTAMENTOS;