CREATE TABLE EQUIPOS
(
	CODEQUIPO VARCHAR2(4),
	NOMBRE VARCHAR2(30) NOT NULL,
	LOCALIDAD VARCHAR2(15),
	CONSTRAINT PK_EQUIPOS PRIMARY KEY (CODEQUIPO)
);

CREATE TABLE JUGADORES
(
	CODJUGADOR VARCHAR2(4),
	NOMBRE VARCHAR2(30) NOT NULL,
	FECHA_NACIMIENTO DATE,
	DEMARCACION VARCHAR2(10),
	CODEQUIPO VARCHAR2(4),
	CONSTRAINT PK_JUGADORES PRIMARY KEY (CODJUGADOR),
	CONSTRAINT FK1_JUGADORES FOREIGN KEY (CODEQUIPO) REFERENCES EQUIPOS(CODEQUIPO)
);

CREATE TABLE PARTIDOS
(
	CODPARTIDO VARCHAR2(4),
	CODEQUIPOLOCAL VARCHAR2(4),
	CODEQUIPOVISITANTE VARCHAR2(4),
	FECHA DATE,
	COMPETICION VARCHAR2(4),
	JORNADA VARCHAR2(20),
	CONSTRAINT PK_PARTIDOS PRIMARY KEY (CODPARTIDO),
	CONSTRAINT FK1_PARTIDOS FOREIGN KEY (CODEQUIPOLOCAL) REFERENCES EQUIPOS(CODEQUIPO),
	CONSTRAINT FK2_PARTIDOS FOREIGN KEY (CODEQUIPOVISITANTE) REFERENCES EQUIPOS(CODEQUIPO),
	CONSTRAINT CHK1_PARTIDOS CHECK (COMPETICION IN('COPA', 'LIGA')),
	CONSTRAINT CHK2_PARTIDOS CHECK (TO_CHAR(FECHA,'MM')NOT IN('07', '08'))
);
CREATE TABLE INCIDENCIAS
(
	NUMINCIDENCIA VARCHAR2(6),
	CODPARTIDO VARCHAR2(4),
	CODJUGADOR VARCHAR2(4),
	MINUTO NUMBER(2),
	TIPO VARCHAR2(20),
	CONSTRAINT PK_INCIDENCIAS PRIMARY KEY (NUMINCIDENCIA),
	CONSTRAINT FK1_INCIDENCIAS FOREIGN KEY (CODPARTIDO) REFERENCES PARTIDOS(CODPARTIDO),
	CONSTRAINT FK2_INCIDENCIAS FOREIGN KEY (CODJUGADOR) REFERENCES JUGADORES(CODJUGADOR),
	CONSTRAINT CHK_INCIDENCIAS CHECK (MINUTO BETWEEN 1 AND 100)
);

ALTER TABLE JUGADORES ADD CONSTRAINT CHK1_JUGADORES CHECK (NOMBRE = INITCAP(NOMBRE));
ALTER TABLE JUGADORES ADD CONSTRAINT CHK2_JUGADORES CHECK (DEMARCACION IN ('PORTERO', 'DEFENSA', 'MEDIO', 'DELANTERO'));


ALTER TABLE EQUIPOS ADD GOLESMARCADOS NUMBER(3);
ALTER TABLE EQUIPOS ADD CONSTRAINT CHK1_EQUIPOS CHECK (REGEXP_LIKE(CODEQUIPO, '^[0-9]'));


ALTER TABLE INCIDENCIAS MODIFY TIPO NOT NULL;

INSERT INTO EQUIPOS VALUES ('2','2','2',0);
INSERT INTO JUGADORES VALUES ('3', 'Jose Maria', sysdate, 'PORTERO','3');
INSERT INTO PARTIDOS VALUES ('2','2','2',TO_DATE('2025-02-01','YYYY-MM-DD'), 'LIGA', '2');

SELECT * FROM PARTIDOS;