CREATE TABLE TEMA
(
	COD_TEMA NUMBER(10),
	DENOMINACION VARCHAR2(20),
	COD_TEMA_PADRE NUMBER(10),
	CONSTRAINT PK_TEMA PRIMARY KEY (COD_TEMA),
	CONSTRAINT CHK_TEMA CHECK (COD_TEMA_PADRE > COD_TEMA)
);

CREATE TABLE AUTOR
(
	COD_AUTOR VARCHAR2(10),
	NOMBRE VARCHAR2(10),
	F_NACIMIENTO DATE,
	LIBRO_PRINCIPAL VARCHAR2(10),
	CONSTRAINT PK_AUTOR PRIMARY KEY (COD_AUTOR)
);

CREATE TABLE LIBRO
(
	COD_LIBRO VARCHAR2(10),
	TITULO VARCHAR2(50),
	F_CREACION DATE,
	COD_TEMA NUMBER(10),
	AUTOR_PRINCIPAL VARCHAR(10),
	CONSTRAINT PK_LIBRO PRIMARY KEY (COD_LIBRO),
	CONSTRAINT FK1_LIBRO FOREIGN KEY (COD_TEMA) REFERENCES TEMA(COD_TEMA),
	CONSTRAINT FK2_LIBRO FOREIGN KEY (AUTOR_PRINCIPAL) REFERENCES AUTOR(COD_AUTOR)
);

CREATE TABLE LIBRO_AUTOR
(
	COD_LIBRO VARCHAR(10),
	COD_AUTOR VARCHAR2(10),
	ORDEN NUMBER(10),
	CONSTRAINT PK_LIBRO_AUTOR PRIMARY KEY (COD_LIBRO, COD_AUTOR),
	CONSTRAINT FK1_LIBRO_AUTOR FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO(COD_LIBRO),
	CONSTRAINT FK2_LIBRO_AUTOR FOREIGN KEY (COD_AUTOR) REFERENCES AUTOR(COD_AUTOR),
	CONSTRAINT CHK_LIBRO_AUTOR CHECK (ORDEN BETWEEN 1 AND 5 )
);
CREATE TABLE EDITORIAL
(
	COD_EDITORIAL VARCHAR2 (10),
	DENOMINACION VARCHAR2(50),
	CONSTRAINT PK_EDITORIAL PRIMARY KEY (COD_EDITORIAL)
);

CREATE TABLE PUBLICACIONES
(
	COD_EDITORIAL VARCHAR2(10),
	COD_LIBRO VARCHAR2(10),
	PRECIO NUMBER(10,2) NOT NULL,
	F_PUBLICACION DATE DEFAULT SYSDATE,
	CONSTRAINT PK_PUBLICACIONES PRIMARY KEY (COD_EDITORIAL, COD_LIBRO),
	CONSTRAINT FK1_PUBLICACIONES FOREIGN KEY (COD_EDITORIAL) REFERENCES EDITORIAL(COD_EDITORIAL) ON DELETE CASCADE,
	CONSTRAINT FK2_PUBLICACIONES FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO(COD_LIBRO),
	CONSTRAINT CHK_PUBLICACIONES CHECK (PRECIO > 0)
);


ALTER TABLE TEMA ADD CONSTRAINT FK1_TEMA FOREIGN KEY (COD_TEMA_PADRE) REFERENCES TEMA(COD_TEMA);
ALTER TABLE AUTOR ADD CONSTRAINT FK1_AUTOR FOREIGN KEY (LIBRO_PRINCIPAL) REFERENCES LIBRO(COD_LIBRO);


-- EJERCICIO 1:
-- Actualmente una editorial no podria publicar mas de un libro ya que tiene una sola primary key y se repetiria por lo que daria error
-- Para arreglar esto habria que agregar de la tabla de publicaciones el atributo f_publicacion a la tabla editorial y añadir como primary key
-- esto hara que tenga una primary key compuesta por lo que si podria repetirse la misma editorial si cambia la fecha

-- EJERCICIO 2:
-- Para borrar todas las tablas he usado drop

DROP TABLE AUTOR CASCADE CONSTRAINTS;
DROP TABLE EDITORIAL CASCADE CONSTRAINTS;
DROP TABLE LIBRO CASCADE CONSTRAINTS;
DROP TABLE LIBRO_AUTOR CASCADE CONSTRAINTS;
DROP TABLE PUBLICACIONES CASCADE CONSTRAINTS;
DROP TABLE TEMA CASCADE CONSTRAINTS;
