CREATE TABLE VEHICULO
(
	MATRICULA VARCHAR2 (7),
	MARCHA VARCHAR2 (10) NOT NULL,
	MODELO VARCHAR2(10) NOT NULL,
	FECHA_COMPRA DATE,
	PRECIO_POR_DIA NUMBER(10,2),
	CONSTRAINT PK_VEHICULO PRIMARY KEY (MATRICULA)
);

CREATE TABLE CLIENTES
(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(30) NOT NULL,
	NACIONALIDAD VARCHAR(30),
	FECHA_NACIMIENTO DATE,
	DIRECCION VARCHAR2(50),
	CONSTRAINT PK_CLIENTES PRIMARY KEY (DNI)
);
CREATE TABLE ALQUILERES
(
	MATRICULA VARCHAR2(7),
	DNI VARCHAR2(10),
	FECHAHORA DATE,
	NUM_DIAS NUMBER (2) NOT NULL,
	KILOMETROS NUMBER(4) DEFAULT 0,
	CONSTRAINT PK_ALQUILERES PRIMARY KEY (MATRICULA, DNI, FECHAHORA),
	CONSTRAINT FK1_ALQUILERES FOREIGN KEY (MATRICULA) REFERENCES VEHICULO(MATRICULA),
	CONSTRAINT FK2_ALQUILERES FOREIGN KEY (DNI) REFERENCES CLIENTES(DNI)
);

ALTER TABLE VEHICULO ADD CONSTRAINT CHK_VEHICULO CHECK (FECHA_COMPRA > TO_DATE('01/01/2001','DD/MM/YYYY'));
ALTER TABLE CLIENTES ADD CONSTRAINT CHK_CLIENTES CHECK (REGEXP_LIKE(DNI,'^[0-9]{8}-[a-zA-Z]$'));
ALTER TABLE VEHICULO ADD CONSTRAINT CHK2_VEHICULO CHECK (REGEXP_LIKE(MATRICULA, '^[0-9]{4}[A-Z]{3}$'));

ALTER TABLE VEHICULO ADD KILOMETROS_TOTALES NUMBER(4);