-- 1
SELECT COUNT(*)
FROM PRODUCTO;

-- 2
SELECT COUNT(*)
FROM FABRICANTE;

-- 3
SELECT COUNT(DISTINCT ID_FABRICANTE)
FROM PRODUCTO;

-- 4
SELECT AVG(PRECIO)
FROM PRODUCTO;

-- 5
SELECT MIN(PRECIO)
FROM PRODUCTO;

-- 6
SELECT MAX(PRECIO) FROM PRODUCTO;

-- 7
SELECT NOMBRE, PRECIO
FROM PRODUCTO
WHERE PRECIO = (SELECT MIN(PRECIO) FROM PRODUCTO);

-- 8
SELECT NOMBRE, PRECIO
FROM PRODUCTO
WHERE PRECIO = (SELECT MAX(PRECIO) FROM PRODUCTO);

-- 9
SELECT SUM(PRECIO) FROM PRODUCTO;

-- 10
SELECT COUNT(P.NOMBRE) FROM PRODUCTO p
JOIN FABRICANTE f 
ON p.ID_FABRICANTE = f.ID
WHERE UPPER(f.NOMBRE) LIKE '%ASUS%';

-- 11
SELECT AVG(P.PRECIO) FROM PRODUCTO p
JOIN FABRICANTE f 
ON p.ID_FABRICANTE = f.ID
WHERE UPPER(f.NOMBRE) LIKE '%ASUS%';

-- 12
SELECT MIN(P.PRECIO) FROM PRODUCTO p
JOIN FABRICANTE f 
ON p.ID_FABRICANTE = f.ID
WHERE UPPER(f.NOMBRE) LIKE '%ASUS%';

-- 13
SELECT MAX(P.PRECIO) FROM PRODUCTO p
JOIN FABRICANTE f 
ON p.ID_FABRICANTE = f.ID
WHERE UPPER(f.NOMBRE) LIKE '%ASUS%';

-- 14
SELECT SUM(P.PRECIO) FROM PRODUCTO p
JOIN FABRICANTE f 
ON p.ID_FABRICANTE = f.ID
WHERE UPPER(f.NOMBRE) LIKE '%ASUS%';

-- 15
SELECT MAX(P.PRECIO), MIN(P.PRECIO), AVG(P.PRECIO), COUNT(*)
FROM PRODUCTO P
JOIN FABRICANTE F
ON P.ID_FABRICANTE = F.ID
WHERE UPPER(F.NOMBRE) = 'CRUCIAL';

-- 16


-- 17
SELECT f.NOMBRE, MAX(p.PRECIO ), MIN(p.PRECIO ), AVG(p.PRECIO )  FROM FABRICANTE f 
JOIN PRODUCTO p 
ON f.ID = p.ID_FABRICANTE
GROUP BY f.NOMBRE;

-- 18
SELECT f.ID , MAX(p.PRECIO ), MIN(p.PRECIO ), AVG(p.PRECIO ), COUNT(p.NOMBRE ) FROM FABRICANTE f 
JOIN PRODUCTO p 
ON f.ID = p.ID_FABRICANTE
GROUP BY f.ID ;

-- 19
SELECT F.NOMBRE, MAX(P.PRECIO), MIN(P.PRECIO), AVG(P.PRECIO), COUNT(*) FROM FABRICANTE F
JOIN PRODUCTO P
ON F.ID = P.ID_FABRICANTE
GROUP BY F.NOMBRE
HAVING AVG(P.PRECIO) > 200;

-- 20
SELECT COUNT(PRECIO) FROM PRODUCTO
WHERE PRECIO >= 180;

-- 21
SELECT ID_FABRICANTE, COUNT(PRECIO) FROM PRODUCTO
WHERE PRECIO >= 180
GROUP BY ID_FABRICANTE;

-- 22
SELECT ID_FABRICANTE, AVG(PRECIO) FROM PRODUCTO
GROUP BY ID_FABRICANTE;

-- 23
SELECT F.NOMBRE, AVG(P.PRECIO) FROM FABRICANTE F
JOIN PRODUCTO P
ON F.ID = P.ID_FABRICANTE
GROUP BY F.NOMBRE;

-- 24
SELECT F.NOMBRE FROM FABRICANTE F
JOIN PRODUCTO P
ON F.ID = P.ID_FABRICANTE
GROUP BY F.NOMBRE
HAVING AVG(P.PRECIO) >= 150;

-- 25
SELECT F.NOMBRE FROM FABRICANTE F
JOIN PRODUCTO P
ON F.ID = P.ID_FABRICANTE
GROUP BY F.NOMBRE
HAVING COUNT(P.ID) >= 2;

-- 26
SELECT F.NOMBRE, COUNT(P.ID) FROM FABRICANTE F
JOIN PRODUCTO P
ON F.ID = P.ID_FABRICANTE
WHERE P.PRECIO >= 220
GROUP BY F.NOMBRE
ORDER BY COUNT(P.ID) DESC ;

-- 27
SELECT F.NOMBRE, COUNT(P.ID) FROM FABRICANTE F
LEFT JOIN PRODUCTO P
ON F.ID = P.ID_FABRICANTE
AND P.PRECIO >= 220
GROUP BY F.NOMBRE
ORDER BY COUNT(P.ID) DESC ;

-- 28
SELECT F.NOMBRE FROM FABRICANTE F
JOIN PRODUCTO P
ON F.ID = P.ID_FABRICANTE
GROUP BY F.NOMBRE
HAVING SUM(P.PRECIO) > 1000;

-- 29
SELECT P.NOMBRE, P.PRECIO, F.NOMBRE FROM PRODUCTO P
JOIN FABRICANTE F
ON P.ID_FABRICANTE = F.ID
WHERE P.PRECIO = (SELECT MAX(P2.PRECIO) FROM PRODUCTO P2
    			  WHERE P2.ID_FABRICANTE = P.ID_FABRICANTE
)
ORDER BY F.NOMBRE ASC;

SELECT * FROM FABRICANTE f ;
SELECT * FROM PRODUCTO p ;