-- 1
SELECT COUNT(c.CODCLI) FROM CLIENTES c 
WHERE c.CODCLI IN (SELECT f.CODCLI FROM FACTURAS f WHERE NVL(f.IVA,0) = 16 );

-- 2
SELECT COUNT(c.CODCLI) FROM CLIENTES c 
WHERE c.CODCLI IN (SELECT f.CODCLI FROM FACTURAS f WHERE NVL(f.IVA,0) != 16 );

-- 3
SELECT COUNT(c.CODCLI) FROM CLIENTES c 
WHERE c.CODCLI IN (SELECT f.CODCLI FROM FACTURAS f WHERE NVL(f.IVA,0) = 16 );

-- 4
SELECT f.FECHA FROM FACTURAS f 
JOIN LINEAS_FAC lf 
ON f.CODFAC = lf.CODFAC
WHERE lf.CANT * lf.PRECIO >= (SELECT MAX(lf2.PRECIO * lf2.CANT) FROM LINEAS_FAC lf2);

SELECT f.FECHA FROM FACTURAS f 
JOIN LINEAS_FAC lf 
ON f.CODFAC = lf.CODFAC
GROUP BY f.FECHA 
ORDER BY SUM(lf.PRECIO * lf.CANT) DESC
FETCH FIRST ROW ONLY;

-- 5
SELECT COUNT(p.CODPUE) FROM PUEBLOS p
WHERE p.CODPUE NOT IN(SELECT c.CODPUE FROM CLIENTES c);

-- 6 (HECHO CON AYUDA)
SELECT COUNT(*)
FROM ARTICULOS a 
WHERE A.STOCK >20 AND A.PRECIO >15 
AND A.CODART NOT IN                   
		(SELECT CODART
		FROM LINEAS_FAC LF
		JOIN FACTURAS F ON F.CODFAC = LF.CODFAC 
		WHERE EXTRACT(YEAR FROM FECHA) = 
			  EXTRACT(YEAR FROM SYSDATE)-1
		AND	
			  EXTRACT (MONTH FROM FECHA) IN (10,11,12))

-- 7
SELECT COUNT(*)
FROM CLIENTES C
WHERE NOT EXISTS (
    SELECT 1 FROM FACTURAS F
    WHERE F.CODCLI = C.CODCLI
    AND EXTRACT(YEAR FROM F.FECHA) = EXTRACT(YEAR FROM SYSDATE)-1
    AND (F.IVA = 0 OR F.IVA IS NULL)
);

-- 8 (HECHO CON AYUDA)
SELECT C.CODCLI, C.NOMBRE
FROM CLIENTES C
JOIN FACTURAS f 
ON C.CODCLI = f.CODCLI
JOIN LINEAS_FAC lf 
ON f.CODFAC = lf.CODFAC
WHERE (
    SELECT SUM(LF.CANT * LF.PRECIO) FROM FACTURAS F
    WHERE F.CODCLI = C.CODCLI
    AND EXTRACT(MONTH FROM F.FECHA) = 11
    AND EXTRACT(YEAR FROM F.FECHA) = EXTRACT(YEAR FROM SYSDATE)-1
) > 60.50 AND NOT EXISTS (
    SELECT 1 FROM FACTURAS F
    	WHERE F.CODCLI = C.CODCLI
    AND EXTRACT(MONTH FROM F.FECHA) = 12
    AND EXTRACT(YEAR FROM F.FECHA) = EXTRACT(YEAR FROM SYSDATE)-1
);

-- 9
SELECT a.CODART , a.DESCRIP, a.PRECIO  FROM ARTICULOS a
ORDER BY a.PRECIO DESC
FETCH FIRST 10 ROWS ONLY;

-- 10
SELECT PR.NOMBRE FROM PROVINCIAS PR
JOIN PUEBLOS PU 
ON PR.CODPRO = PU.CODPRO
JOIN CLIENTES C 
ON PU.CODPUE = C.CODPUE
GROUP BY PR.NOMBRE
ORDER BY COUNT(*) DESC
FETCH FIRST 1 ROW ONLY;

-- 12
SELECT CODART, DESCRIP
FROM ARTICULOS
WHERE PRECIO > 3000 * (SELECT MIN(PRECIO) FROM ARTICULOS);

-- 13
SELECT C.NOMBRE FROM CLIENTES C
JOIN FACTURAS F 
ON C.CODCLI = F.CODCLI
JOIN LINEAS_FAC LF 
ON F.CODFAC = LF.CODFAC
GROUP BY C.NOMBRE
ORDER BY SUM(LF.CANT * LF.PRECIO) DESC
FETCH FIRST 1 ROW ONLY;

-- 14
SELECT A.CODART, A.DESCRIP
FROM ARTICULOS A
JOIN LINEAS_FAC LF ON A.CODART = LF.CODART
JOIN FACTURAS F ON LF.CODFAC = F.CODFAC
GROUP BY A.CODART, A.DESCRIP, A.PRECIO
HAVING A.PRECIO > (SELECT AVG(PRECIO) FROM ARTICULOS)
AND COUNT(F.CODCLI) > 5;

SELECT * FROM LINEAS_FAC lf 