-- 1.1.7.2
-- 8
SELECT * FROM PRODUCTO p
WHERE p.PRECIO >= ALL (SELECT p2.PRECIO FROM PRODUCTO p2);

-- 9 
SELECT * FROM PRODUCTO p
WHERE p.PRECIO <= ALL (SELECT p2.PRECIO FROM PRODUCTO p2);

-- 10
SELECT f.NOMBRE  FROM FABRICANTE f 
WHERE f.ID = ANY (SELECT p.ID_FABRICANTE FROM PRODUCTO p);


-- 1.1.7.3
-- 12

SELECT f.NOMBRE  FROM FABRICANTE f 
WHERE f.ID IN (SELECT p.ID_FABRICANTE FROM PRODUCTO p);

-- 13
SELECT f.NOMBRE  FROM FABRICANTE f 
WHERE f.ID NOT IN (SELECT p.ID_FABRICANTE FROM PRODUCTO p);

-- 1.1.7.4
-- 14
SELECT f.NOMBRE  FROM FABRICANTE f 
WHERE EXISTS (SELECT p.ID_FABRICANTE FROM PRODUCTO p 
				WHERE f.ID = p.ID_FABRICANTE );

-- 15
SELECT f.NOMBRE  FROM FABRICANTE f 
WHERE NOT EXISTS (SELECT p.ID_FABRICANTE FROM PRODUCTO p 
				WHERE f.ID = p.ID_FABRICANTE );