-- 1
-- SQL1
SELECT P.NOMBRE, P.PRECIO, F.NOMBRE
FROM PRODUCTO P, FABRICANTE F
WHERE P.ID_FABRICANTE = F.ID;

-- SQL2
SELECT P.NOMBRE, P.PRECIO, F.NOMBRE
FROM PRODUCTO P
JOIN FABRICANTE F
ON P.ID_FABRICANTE = F.ID;

-- 2
-- SQL1
SELECT P.NOMBRE, P.PRECIO, F.NOMBRE
FROM PRODUCTO P, FABRICANTE F
WHERE P.ID_FABRICANTE = F.ID
ORDER BY F.NOMBRE ASC;

-- SQL2
SELECT P.NOMBRE, P.PRECIO, F.NOMBRE
FROM PRODUCTO P
JOIN FABRICANTE F
ON P.ID_FABRICANTE = F.ID
ORDER BY F.NOMBRE ASC;

-- 3
-- SQL1
SELECT P.ID, P.NOMBRE, F.ID, F.NOMBRE
FROM PRODUCTO P, FABRICANTE F
WHERE P.ID_FABRICANTE = F.ID;

-- SQL2
SELECT P.ID, P.NOMBRE, F.ID, F.NOMBRE
FROM PRODUCTO P
JOIN FABRICANTE F
ON P.ID_FABRICANTE = F.ID;

-- 4
-- SQL1
SELECT P.NOMBRE, P.PRECIO, F.NOMBRE
FROM PRODUCTO P, FABRICANTE F
WHERE P.ID_FABRICANTE = F.ID
ORDER BY P.PRECIO ASC
FETCH FIRST 1 ROW ONLY;

-- SQL2
SELECT P.NOMBRE, P.PRECIO, F.NOMBRE
FROM PRODUCTO P
JOIN FABRICANTE F
ON P.ID_FABRICANTE = F.ID
ORDER BY P.PRECIO ASC
FETCH FIRST 1 ROW ONLY;

-- 5
-- SQL1
SELECT P.NOMBRE, P.PRECIO, F.NOMBRE
FROM PRODUCTO P, FABRICANTE F
WHERE P.ID_FABRICANTE = F.ID
ORDER BY P.PRECIO DESC
FETCH FIRST 1 ROW ONLY;

-- SQL2
SELECT P.NOMBRE, P.PRECIO, F.NOMBRE
FROM PRODUCTO P
JOIN FABRICANTE F
ON P.ID_FABRICANTE = F.ID
ORDER BY P.PRECIO DESC
FETCH FIRST 1 ROW ONLY;

-- 6
-- SQL1
SELECT P.NOMBRE
FROM PRODUCTO P, FABRICANTE F
WHERE P.ID_FABRICANTE = F.ID
AND F.NOMBRE = 'LENOVO';

-- SQL2
SELECT P.NOMBRE
FROM PRODUCTO P
JOIN FABRICANTE F
ON P.ID_FABRICANTE = F.ID
WHERE F.NOMBRE = 'LENOVO';

-- 7
-- SQL1
SELECT P.NOMBRE
FROM PRODUCTO P, FABRICANTE F
WHERE P.ID_FABRICANTE = F.ID
AND F.NOMBRE = 'CRUCIAL'
AND P.PRECIO > 200;

-- SQL2
SELECT P.NOMBRE
FROM PRODUCTO P
JOIN FABRICANTE F
ON P.ID_FABRICANTE = F.ID
WHERE F.NOMBRE = 'CRUCIAL'
AND P.PRECIO > 200;

-- 8
-- SQL1
SELECT P.NOMBRE
FROM PRODUCTO P, FABRICANTE F
WHERE P.ID_FABRICANTE = F.ID
AND (F.NOMBRE = 'ASUS'
OR F.NOMBRE = 'HEWLETT-PACKARD'
OR F.NOMBRE = 'SEAGATE');

-- SQL2
SELECT P.NOMBRE
FROM PRODUCTO P
JOIN FABRICANTE F
ON P.ID_FABRICANTE = F.ID
WHERE F.NOMBRE = 'ASUS'
OR F.NOMBRE = 'HEWLETT-PACKARD'
OR F.NOMBRE = 'SEAGATE';

-- 9
-- SQL1
SELECT P.NOMBRE
FROM PRODUCTO P, FABRICANTE F
WHERE P.ID_FABRICANTE = F.ID
AND F.NOMBRE IN ('ASUS','HEWLETT-PACKARD','SEAGATE');

-- SQL2
SELECT P.NOMBRE
FROM PRODUCTO P
JOIN FABRICANTE F
ON P.ID_FABRICANTE = F.ID
WHERE F.NOMBRE IN ('ASUS','HEWLETT-PACKARD','SEAGATE');

-- 10
-- SQL1
SELECT P.NOMBRE, P.PRECIO
FROM PRODUCTO P, FABRICANTE F
WHERE P.ID_FABRICANTE = F.ID
AND F.NOMBRE LIKE '%E';

-- SQL2
SELECT P.NOMBRE, P.PRECIO
FROM PRODUCTO P
JOIN FABRICANTE F
ON P.ID_FABRICANTE = F.ID
WHERE F.NOMBRE LIKE '%E';

-- 11
-- SQL1
SELECT P.NOMBRE, P.PRECIO
FROM PRODUCTO P, FABRICANTE F
WHERE P.ID_FABRICANTE = F.ID
AND LOWER(F.NOMBRE) LIKE '%W%';

-- SQL2
SELECT P.NOMBRE, P.PRECIO
FROM PRODUCTO P
JOIN FABRICANTE F
ON P.ID_FABRICANTE = F.ID
WHERE LOWER(F.NOMBRE) LIKE '%W%';

-- 12
-- SQL1
SELECT P.NOMBRE, P.PRECIO, F.NOMBRE
FROM PRODUCTO P, FABRICANTE F
WHERE P.ID_FABRICANTE = F.ID
AND P.PRECIO >= 180
ORDER BY P.PRECIO DESC, P.NOMBRE ASC;

-- SQL2
SELECT P.NOMBRE, P.PRECIO, F.NOMBRE
FROM PRODUCTO P
JOIN FABRICANTE F
ON P.ID_FABRICANTE = F.ID
WHERE P.PRECIO >= 180
ORDER BY P.PRECIO DESC, P.NOMBRE ASC;

-- 13
-- SQL1
SELECT DISTINCT F.ID, F.NOMBRE
FROM FABRICANTE F, PRODUCTO P
WHERE F.ID = P.ID_FABRICANTE;

-- SQL2
SELECT DISTINCT F.ID, F.NOMBRE
FROM FABRICANTE F
JOIN PRODUCTO P
ON F.ID = P.ID_FABRICANTE;


SELECT * FROM FABRICANTE;
SELECT * FROM PRODUCTO;