-- 1
-- LEFT JOIN
SELECT F.NOMBRE, P.NOMBRE
FROM FABRICANTE F
LEFT JOIN PRODUCTO P
ON F.ID = P.ID_FABRICANTE;

-- RIGHT JOIN
SELECT F.NOMBRE, P.NOMBRE
FROM PRODUCTO P
RIGHT JOIN FABRICANTE F
ON F.ID = P.ID_FABRICANTE;

-- 2
-- LEFT JOIN
SELECT F.NOMBRE
FROM FABRICANTE F
LEFT JOIN PRODUCTO P
ON F.ID = P.ID_FABRICANTE
WHERE P.ID IS NULL;

-- RIGHT JOIN
SELECT F.NOMBRE
FROM PRODUCTO P
RIGHT JOIN FABRICANTE F
ON F.ID = P.ID_FABRICANTE
WHERE P.ID IS NULL;

-- 3
-- NO YA QUE LA TABLA PRODUCTO TIENE UNA CLAVE FORANEA QUE NO PUEDE SER NULA




SELECT * FROM FABRICANTE;
SELECT * FROM PRODUCTO;