CREATE TABLE GAMA(
	GAMA VARCHAR (50),
	DESCRIPCION_TEXTO VARCHAR (50),
	DESCRIPCION_HTML VARCHAR (50),
	IMAGEN VARCHAR (256),
	CONSTRAINT PK_GAMA PRIMARY KEY (GAMA)
);

CREATE TABLE OFICINA (
	CODIGO_OFICINA VARCHAR (10),
	CIUDAD VARCHAR (30),
	PAIS VARCHAR (50),
	REGION VARCHAR (50),
	CODIGO_POSTAL VARCHAR (10),
	TELEFONO VARCHAR (20),
	LINEA_DIRECCION1 VARCHAR (50),
	LINEA_DIRECCION2 VARCHAR (50),
	CONSTRAINT PK_OFICINA PRIMARY KEY (CODIGO_OFICINA)
);

CREATE TABLE PRODUCTO
(
	CODIGO_PRODUCTO VARCHAR(15),
	NOMBRE VARCHAR (70),
	GAMA VARCHAR (50),
	DIMENSIONES VARCHAR(25),
	PROVEEDOR VARCHAR (50),
	DESCRIPCION VARCHAR (50),
	CANTIDAD_EN_STOCK NUMERIC (9),
	PRECIO_VENTA NUMERIC (15,2),
	PRECIO_PROVEEDOR NUMERIC (15,2),
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO_PRODUCTO),
	CONSTRAINT FK_GAMA FOREIGN KEY (GAMA) REFERENCES GAMA(GAMA)    
);

CREATE TABLE EMPLEADO
(
	CODIGO_EMPLEADO NUMERIC(11),
	NOMBRE VARCHAR(50),
	APELLIDO1 VARCHAR(50),
	APELLIDO2 VARCHAR(50),
	EXTENSION VARCHAR(10),
	EMAIL VARCHAR(100),
	CODIGO_OFICINA VARCHAR(10),
	CODIGO_JEFE NUMERIC(11),
	PUESTO VARCHAR(50),
	CONSTRAINT PK_EMPLEADO PRIMARY KEY (CODIGO_EMPLEADO),
	CONSTRAINT FK1_EMPLEADO FOREIGN KEY (CODIGO_OFICINA) REFERENCES OFICINA(CODIGO_OFICINA),
	CONSTRAINT FK2_EMPLEADO FOREIGN KEY (CODIGO_JEFE) REFERENCES EMPLEADO(CODIGO_EMPLEADO)
);

CREATE TABLE CLIENTE
(
	CODIGO_CLIENTE NUMERIC(11),
	NOMBRE_CLIENTE VARCHAR(50),
	NOMBRE_CONTACTO VARCHAR(30),
	APELLIDO_CONTACTO VARCHAR (30),
	TELEFONO VARCHAR(15),
	FAX VARCHAR(15),
	LINEA_DIRECCION1 VARCHAR(50),
	LINEA_DIRECCION2 VARCHAR(50),
	CIUDAD VARCHAR(50),
	REGION VARCHAR(50),
	PAIS VARCHAR(50),
	CODIGO_POSTAL VARCHAR(10),
	CODIGO_EMPLEADO_REP_VENTAS NUMERIC(11),
	LIMITE_CREDITO NUMERIC(15,2),
	CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO_CLIENTE),
	CONSTRAINT FK_CLIENTE FOREIGN KEY (CODIGO_EMPLEADO_REP_VENTAS) REFERENCES EMPLEADO(CODIGO_EMPLEADO)
);

CREATE TABLE PEDIDO
(
	CODIGO_PEDIDO NUMERIC(11),
	FECHA_PEDIDO DATE,
	FECHA_ESPERADA DATE,
	FECHA_ENTREGA DATE,
	ESTADO VARCHAR(15),
	COMENTARIOS VARCHAR(50),
	CODIGO_CLIENTE NUMERIC(11),
	CONSTRAINT PK_PEDIDO PRIMARY KEY (CODIGO_PEDIDO),
	CONSTRAINT FK_PEDIDO FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE)
);

CREATE TABLE DETALLE_PEDIDO(
	CODIGO_PEDIDO NUMERIC (11),
	CODIGO_PRODUCTO VARCHAR (15),
	CANTIDAD NUMERIC (11),
	PRECIO_UNIDAD NUMERIC (15,2),
	NUMERO_LINEA NUMERIC (6),
	CONSTRAINT FK1_PEDIDO FOREIGN KEY (CODIGO_PEDIDO) REFERENCES PEDIDO (CODIGO_PEDIDO),
	CONSTRAINT FK2_PEDIDO FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO)
);

CREATE TABLE PAGO
(
	CODIGO_CLIENTE NUMERIC(11),
	FORMA_PAGO VARCHAR(40),
	ID_TRANSACCION VARCHAR(50),
	FECHA_PAGO DATE,
	TOTAL NUMERIC(15,2),
	CONSTRAINT PK_PAGO PRIMARY KEY (ID_TRANSACCION),
	CONSTRAINT FK_PAGO FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE)
);
