-- 11
SELECT * FROM EMPLEADO E 
LEFT JOIN DEPARTAMENTO D 
ON E.ID_DEPARTAMENTO = D.ID 
ORDER BY E.ID ASC;

SELECT * FROM EMPLEADO E, DEPARTAMENTO D
WHERE E.ID_DEPARTAMENTO(+) = D.ID 
ORDER BY E.ID ASC;

-- 12
SELECT * FROM EMPLEADO E LEFT JOIN DEPARTAMENTO D 
ON E.ID_DEPARTAMENTO = D.ID WHERE E.ID_DEPARTAMENTO IS NULL 
ORDER BY E.ID ASC;

SELECT * FROM EMPLEADO
WHERE ID_DEPARTAMENTO IS NULL
ORDER BY ID ASC;

-- 13
SELECT * FROM DEPARTAMENTO D LEFT JOIN EMPLEADO E 
ON E.ID_DEPARTAMENTO = D.ID WHERE E.ID_DEPARTAMENTO IS NULL;
