-- 1
SELECT c.NOMBRE  FROM CLIENTES c JOIN PUEBLOS p 
ON c.CODPUE = p.CODPUE;

-- 2
SELECT p.NOMBRE PUEBLO, p2.NOMBRE PROVINCIA FROM PUEBLOS p JOIN PROVINCIAS p2 
ON p.CODPRO = p2.CODPRO;

-- 3
SELECT c.NOMBRE CLIENTE, p.NOMBRE PUEBLO, p2.NOMBRE PROVINCIA FROM CLIENTES c JOIN PUEBLOS p 
ON c.CODPUE = p.CODPUE
JOIN PROVINCIAS p2 
ON p.CODPRO = p2.CODPRO;

-- 4
SELECT DISTINCT p2.NOMBRE PROVINCIA FROM CLIENTES c JOIN PUEBLOS p 
ON c.CODPUE = p.CODPUE
JOIN PROVINCIAS p2 
ON p.CODPRO = p2.CODPRO;

-- 5
SELECT DISTINCT a.DESCRIP FROM ARTICULOS a JOIN LINEAS_FAC lf 
ON a.CODART = lf.CODART
WHERE lf.CANT > 10;

-- 6
SELECT f.FECHA, a.CODART , lf.CANT FROM FACTURAS f JOIN LINEAS_FAC lf 
ON f.CODFAC = lf.CODFAC
JOIN ARTICULOS a 
ON lf.CODART = a.CODART
ORDER BY f.FECHA DESC, a.CODART ASC, CANT DESC;

-- 7
SELECT f.CODFAC, f.FECHA  FROM FACTURAS f JOIN CLIENTES c 
ON f.CODCLI = c.CODCLI
WHERE c.CODPOSTAL LIKE '%7%';

-- 8
SELECT DISTINCT f.CODFAC, f.FECHA, c.NOMBRE  FROM FACTURAS f JOIN CLIENTES c 
ON f.CODCLI = c.CODCLI;

-- 9
SELECT f.CODFAC , f.FECHA , f.IVA , f.DTO , c.NOMBRE  FROM FACTURAS f JOIN CLIENTES c 
ON f.CODCLI = c.CODCLI
WHERE f.IVA IS NULL OR f.IVA = 0 OR f.DTO IS NULL;

-- 10
SELECT a.DESCRIP , a.PRECIO  FROM ARTICULOS a JOIN LINEAS_FAC lf
ON a.CODART = lf.CODART
WHERE lf.PRECIO < a.PRECIO;

-- 11
SELECT f.CODFAC , f.FECHA , f.IVA , f.DTO , a.DESCRIP , a.PRECIO , lf.CANT ,lf.DTO FROM FACTURAS f JOIN LINEAS_FAC lf 
ON f.CODFAC = lf.CODFAC
JOIN ARTICULOS a 
ON lf.CODART = a.CODART
ORDER BY f.CODFAC ASC;


-- 12
SELECT c.NOMBRE CLIENTE , f.CODFAC , f.FECHA , f.IVA , f.DTO , a.DESCRIP , a.PRECIO , lf.CANT ,lf.DTO FROM FACTURAS f JOIN LINEAS_FAC lf 
ON f.CODFAC = lf.CODFAC
JOIN ARTICULOS a 
ON lf.CODART = a.CODART
JOIN CLIENTES c 
ON f.CODCLI = c.CODCLI
ORDER BY f.CODFAC ASC;

-- 13
SELECT c.NOMBRE  FROM CLIENTES c JOIN PUEBLOS p 
ON c.CODPUE = p.CODPUE
JOIN PROVINCIAS p2 
ON p.CODPRO = p2.CODPRO
WHERE UPPER(p2.NOMBRE) LIKE '%MA%';

-- 14
SELECT c.CODCLI  FROM CLIENTES c JOIN FACTURAS f 
ON c.CODCLI = f.CODCLI
JOIN LINEAS_FAC lf 
ON f.CODFAC = lf.CODFAC
JOIN ARTICULOS a 
ON lf.CODART = a.CODART
WHERE a.STOCK < a.STOCK_MIN;

SELECT a.CODART  FROM ARTICULOS a 
WHERE STOCK < a.STOCK_MIN ;

-- 15
SELECT DISTINCT a.DESCRIP  FROM ARTICULOS a JOIN LINEAS_FAC lf 
ON a.CODART = lf.CODART;

-- 16
SELECT lf.PRECIO SIN, lf.PRECIO - lf.PRECIO * (lf.DTO / 100) CON FROM ARTICULOS  a JOIN LINEAS_FAC lf 
ON a.CODART = lf.CODART;

-- 17
SELECT a.DESCRIP  FROM ARTICULOS a JOIN LINEAS_FAC lf 
ON a.CODART = lf.CODART
JOIN FACTURAS f 
ON lf.CODFAC = f.CODFAC
JOIN CLIENTES c
ON f.CODCLI = c.CODCLI
JOIN PUEBLOS p 
ON c.CODPUE = p.CODPUE
JOIN PROVINCIAS p2
ON p.CODPRO = p2.CODPRO
WHERE UPPER(p2.NOMBRE) LIKE '%A';

-- 18
SELECT DISTINCT c.NOMBRE  FROM CLIENTES c JOIN FACTURAS f 
ON c.CODCLI = f.CODCLI
JOIN LINEAS_FAC lf 
ON f.CODFAC = lf.CODFAC
WHERE f.DTO > 10;

-- 19
SELECT DISTINCT c.NOMBRE  FROM CLIENTES c JOIN FACTURAS f 
ON c.CODCLI = f.CODCLI
JOIN LINEAS_FAC lf 
ON f.CODFAC = lf.CODFAC
WHERE f.DTO > 10 OR lf.DTO > 10;

-- 20
SELECT a.DESCRIP, lf.CANT , lf.PRECIO FROM ARTICULOS a JOIN LINEAS_FAC lf 
ON a.CODART = lf.CODART
JOIN FACTURAS f 
ON lf.CODFAC = f.CODFAC
JOIN CLIENTES c 
ON f.CODCLI = c.CODCLI
WHERE UPPER(c.NOMBRE) LIKE '%MARIA MERCEDES';

SELECT * FROM ARTICULOS;
SELECT * FROM CLIENTES;
SELECT * FROM FACTURAS;
SELECT * FROM LINEAS_FAC;
SELECT * FROM PROVINCIAS;
SELECT * FROM PUEBLOS;