-- 1
SELECT AVG(DTO) FROM FACTURAS;

-- 2
SELECT AVG(DTO) FROM FACTURAS
WHERE DTO IS NOT NULL;

-- 3
SELECT AVG(NVL(DTO,0)) FROM FACTURAS;

-- 4
SELECT COUNT(CODFAC) FROM FACTURAS;

-- 5
SELECT COUNT(p.CODPRO) FROM PUEBLOS p
JOIN PROVINCIAS p2 
ON p.CODPRO = p2.CODPRO
WHERE UPPER(p2.NOMBRE) LIKE 'VALENCIA';

-- 6
SELECT SUM(PRECIO * STOCK) FROM ARTICULOS;

-- 7
SELECT COUNT(DISTINCT c.CODPUE) FROM PUEBLOS p 
JOIN CLIENTES c 
ON p.CODPUE = c.CODPUE
WHERE c.CODPOSTAL LIKE '12%';

-- 8
SELECT MAX(a.STOCK), MIN(a.STOCK),MAX(a.STOCK) - MIN(a.STOCK) MAX 
FROM ARTICULOS a 
WHERE a.PRECIO BETWEEN 9 AND 12;

-- 9
SELECT AVG(PRECIO) FROM ARTICULOS
WHERE STOCK > 10;

-- 10
SELECT MAX(FECHA), MIN(FECHA) FROM FACTURAS
WHERE CODCLI = 210;

-- 11
SELECT COUNT(CODART) FROM ARTICULOS
WHERE STOCK IS NULL;

-- 12
SELECT TO_CHAR(COUNT(LINEA)) FROM LINEAS_FAC
WHERE DTO IS NULL;

-- 13
SELECT CODCLI, COUNT(CODFAC) FROM FACTURAS
GROUP BY CODCLI;

-- 14
SELECT CODCLI, COUNT(CODFAC) FROM FACTURAS
GROUP BY CODCLI
HAVING COUNT(CODFAC) >= 2;

-- 15
SELECT SUM(CANT * PRECIO) FROM LINEAS_FAC;

-- 16
SELECT SUM(CANT * PRECIO) FROM LINEAS_FAC
WHERE CODART LIKE '%A%';

-- 17
SELECT FECHA, COUNT(CODFAC) FROM FACTURAS
GROUP BY FECHA;

-- 18
SELECT p.NOMBRE, COUNT(c.CODPUE) FROM CLIENTES c
JOIN PUEBLOS p
ON c.CODPUE = p.CODPUE
GROUP BY p.NOMBRE
ORDER BY COUNT(c.CODPUE) DESC;

-- 19
SELECT p.NOMBRE, COUNT(c.CODPUE) FROM CLIENTES c
JOIN PUEBLOS p
ON c.CODPUE = p.CODPUE
GROUP BY p.NOMBRE
HAVING COUNT(c.CODPUE) > 2
ORDER BY COUNT(c.CODPUE) DESC;

-- 20
SELECT a.CODART , SUM(lf.CANT) , a.DESCRIP FROM LINEAS_FAC lf 
JOIN ARTICULOS a 
ON lf.CODART = a.CODART
WHERE a.CODART LIKE 'P%'
GROUP BY a.CODART, a.DESCRIP;

-- 21
SELECT a.CODART , SUM(lf.CANT) , a.DESCRIP, MAX(a.PRECIO) - MIN(A.PRECIO) DIFERENCIA FROM LINEAS_FAC lf 
JOIN ARTICULOS a 
ON lf.CODART = a.CODART
WHERE a.CODART LIKE 'P%'
GROUP BY a.CODART, a.DESCRIP;

-- 22
SELECT a.DESCRIP, SUM(lf.PRECIO * lf.CANT) FROM ARTICULOS a 
JOIN LINEAS_FAC lf 
ON a.CODART = lf.CODART
GROUP BY a.DESCRIP 
HAVING SUM(lf.PRECIO * lf.CANT) > 10000;

-- 23
SELECT f.CODFAC, COUNT(f.CODCLI) FROM FACTURAS f
WHERE f.CODCLI BETWEEN 150 AND 300
GROUP BY f.CODFAC;

-- 24
SELECT AVG(lf.PRECIO * lf.CANT) FROM LINEAS_FAC lf;

SELECT * FROM ARTICULOS;
SELECT * FROM CLIENTES;
SELECT * FROM FACTURAS;
SELECT * FROM LINEAS_FAC;
SELECT * FROM PROVINCIAS;
SELECT * FROM PUEBLOS;

