-- 1
SELECT COUNT(a.COSTEBASICO ) FROM ASIGNATURA a; 

-- 2
SELECT t.NOMBRE, COUNT(a.IDASIGNATURA ) FROM TITULACION t
JOIN ASIGNATURA a
ON t.IDTITULACION = a.IDTITULACION
GROUP BY T.NOMBRE;

-- 3
SELECT t.NOMBRE, SUM(a.COSTEBASICO ) FROM TITULACION t
JOIN ASIGNATURA a
ON t.IDTITULACION = a.IDTITULACION
GROUP BY T.NOMBRE;

-- 4
SELECT t.NOMBRE, SUM(a.COSTEBASICO * 1.07) FROM TITULACION t
JOIN ASIGNATURA a
ON t.IDTITULACION = a.IDTITULACION
WHERE UPPER(T.NOMBRE) LIKE 'MATEMATICAS'
GROUP BY T.NOMBRE;

-- 5
SELECT IDASIGNATURA, COUNT(IDALUMNO) FROM ALUMNO_ASIGNATURA
GROUP BY IDASIGNATURA;

-- 6
SELECT a2.NOMBRE  , COUNT(A.IDALUMNO) FROM ALUMNO_ASIGNATURA A
JOIN ASIGNATURA a2
ON A.IDASIGNATURA = A2.IDASIGNATURA
GROUP BY a2.NOMBRE ;

-- 7
SELECT P.NOMBRE,
SUM(A.COSTEBASICO * (1 + (AA.NUMEROMATRICULA-1)*0.10)) PAGA FROM PERSONA P
JOIN ALUMNO AL 
ON P.DNI = AL.DNI
JOIN ALUMNO_ASIGNATURA AA 
ON AL.IDALUMNO = AA.IDALUMNO
JOIN ASIGNATURA A 
ON AA.IDASIGNATURA = A.IDASIGNATURA
GROUP BY P.NOMBRE;

--8
SELECT T.NOMBRE, AVG(A.COSTEBASICO) FROM TITULACION T
JOIN ASIGNATURA A
ON T.IDTITULACION = A.IDTITULACION
GROUP BY T.NOMBRE
HAVING SUM(A.COSTEBASICO) > 60;

--9
SELECT T.NOMBRE FROM TITULACION T
JOIN ASIGNATURA A 
ON T.IDTITULACION = A.IDTITULACION
JOIN ALUMNO_ASIGNATURA AA 
ON A.IDASIGNATURA = AA.IDASIGNATURA
GROUP BY T.NOMBRE
HAVING COUNT(DISTINCT AA.IDALUMNO) > 3;

-- 10
SELECT CIUDAD, COUNT(DNI) FROM PERSONA
GROUP BY CIUDAD;

-- 11
SELECT P.NOMBRE, COUNT(A.IDASIGNATURA) FROM PERSONA P
JOIN PROFESOR PR 
ON P.DNI = PR.DNI
JOIN ASIGNATURA A 
ON PR.IDPROFESOR = A.IDPROFESOR
GROUP BY P.NOMBRE;

-- 12
SELECT P.NOMBRE, COUNT(DISTINCT AA.IDALUMNO) FROM PERSONA P
JOIN PROFESOR PR 
ON P.DNI = PR.DNI
JOIN ASIGNATURA A 
ON PR.IDPROFESOR = A.IDPROFESOR
JOIN ALUMNO_ASIGNATURA AA 
ON A.IDASIGNATURA = AA.IDASIGNATURA
GROUP BY P.NOMBRE
HAVING COUNT(DISTINCT AA.IDALUMNO) >= 2;

-- 13
SELECT SUM(COSTEBASICO) AS SUMA
FROM ASIGNATURA
GROUP BY CUATRIMESTRE
ORDER BY SUMA DESC
FETCH FIRST 1 ROW ONLY;

-- 14
SELECT SUM(COSTEBASICO) FROM ASIGNATURA;

-- 15
SELECT COUNT(IDASIGNATURA ) FROM ASIGNATURA;

-- 16
SELECT MAX(COSTEBASICO), MIN(COSTEBASICO) FROM ASIGNATURA;

-- 17
SELECT COUNT(DISTINCT CREDITOS) FROM ASIGNATURA;

-- 18
SELECT COUNT(DISTINCT CURSO) FROM ASIGNATURA;

-- 19
SELECT COUNT(DISTINCT CIUDAD) FROM PERSONA;

-- 20
SELECT NOMBRE, CREDITOS*10 AS HORAS FROM ASIGNATURA;

-- 21
SELECT NOMBRE FROM ASIGNATURA
WHERE IDTITULACION IS NULL;

-- 22
SELECT NOMBRE || ' ' || APELLIDO NOMBRECOMPLETO, TELEFONO,
DIRECCIONCALLE || ' ' || DIRECCIONNUM DIRECCION
FROM PERSONA;

--23
SELECT NOMBRE, FECHA_NACIMIENTO + 1 FROM PERSONA;

--24
SELECT NOMBRE, FLOOR(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12) EDAD FROM PERSONA;

--25
SELECT * FROM PERSONA
WHERE FLOOR(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12) > 25
ORDER BY APELLIDO, NOMBRE;

--26
SELECT P.NOMBRE, P.APELLIDO FROM PERSONA P
JOIN PROFESOR PR 
ON P.DNI = PR.DNI
JOIN ALUMNO AL 
ON P.DNI = AL.DNI;

--27
SELECT SUM(A.CREDITOS) FROM ASIGNATURA A
JOIN TITULACION T
ON A.IDTITULACION = T.IDTITULACION
WHERE T.NOMBRE = 'Matematicas';

--28
SELECT COUNT(A.IDASIGNATURA) FROM ASIGNATURA A
JOIN TITULACION T
ON A.IDTITULACION = T.IDTITULACION
WHERE T.NOMBRE = 'Matematicas';

--29
SELECT p.NOMBRE , SUM(A.COSTEBASICO * (1 + (AA.NUMEROMATRICULA-1)*0.10))
FROM ASIGNATURA a 
JOIN ALUMNO_ASIGNATURA aa 
ON AA.IDASIGNATURA = A.IDASIGNATURA
JOIN ALUMNO a2
ON aa.IDALUMNO = a2.IDALUMNO
JOIN PERSONA p 
ON a2.DNI = p.DNI
GROUP BY p.NOMBRE ;


--30
SELECT IDASIGNATURA, COUNT(IDALUMNO) FROM ALUMNO_ASIGNATURA
GROUP BY IDASIGNATURA;

SELECT * FROM ALUMNO;
SELECT * FROM ASIGNATURA;
SELECT * FROM ALUMNO_ASIGNATURA aa ;
SELECT * FROM PERSONA;
SELECT * FROM PROFESOR;
SELECT * FROM TITULACION;