-- 1
SELECT A.NOMBRE, A.COSTEBASICO FROM TITULACION T RIGHT JOIN ASIGNATURA A
ON A.IDASIGNATURA = T.IDTITULACION
WHERE A.IDTITULACION IS NOT NULL
ORDER BY A.COSTEBASICO DESC, A.NOMBRE ASC;

-- 2
SELECT PE.NOMBRE, PE.APELLIDO FROM PERSONA PE JOIN PROFESOR PR
ON PE.DNI = PR.DNI;

SELECT PE.NOMBRE, PE.APELLIDO FROM PERSONA PE, PROFESOR PR
WHERE PE.DNI = PR.DNI;

-- 3
SELECT A.NOMBRE FROM ASIGNATURA A JOIN PROFESOR PR
ON A.IDPROFESOR = PR.IDPROFESOR
JOIN PERSONA PE ON PE.DNI = PR.DNI
WHERE UPPER(PE.CIUDAD) LIKE 'SEVILLA';

-- 4
SELECT PE.NOMBRE, PE.APELLIDO FROM PERSONA PE JOIN ALUMNO A
ON PE.DNI = A.DNI;

SELECT PE.NOMBRE, PE.APELLIDO FROM PERSONA PE, ALUMNO A
WHERE PE.DNI = A.DNI;

-- 5
SELECT P.DNI, P.NOMBRE, P.APELLIDO FROM PERSONA p JOIN ALUMNO a 
ON p.DNI = a.DNI
WHERE UPPER(p.CIUDAD) LIKE 'SEVILLA';

-- 6
SELECT P.DNI, P.NOMBRE, P.APELLIDO FROM PERSONA p JOIN ALUMNO a 
ON p.DNI = a.DNI
JOIN ALUMNO_ASIGNATURA aa
ON a.IDALUMNO = aa.IDALUMNO
JOIN ASIGNATURA a2
ON aa.IDASIGNATURA = a2.IDASIGNATURA
WHERE UPPER(a2.NOMBRE) LIKE 'SEGURIDAD VIAL';

-- 7
SELECT A.IDTITULACION FROM ASIGNATURA A JOIN ALUMNO_ASIGNATURA aa 
ON A.IDASIGNATURA = aa.IDASIGNATURA
JOIN ALUMNO a2
ON aa.IDALUMNO = a2.IDALUMNO
JOIN PERSONA p 
ON a2.DNI = p.DNI
WHERE P.DNI LIKE '20202020A';

-- 8
SELECT A.NOMBRE  FROM ASIGNATURA A JOIN ALUMNO_ASIGNATURA aa
ON A.IDASIGNATURA = aa.IDASIGNATURA
JOIN ALUMNO a2 
ON aa.IDALUMNO = a2.IDALUMNO
JOIN PERSONA p 
ON a2.DNI = p.DNI
WHERE p.NOMBRE LIKE 'Rosa' AND p.APELLIDO LIKE 'Garcia';

-- 9
SELECT A.DNI FROM ALUMNO A JOIN ALUMNO_ASIGNATURA aa 
ON A.IDALUMNO = aa.IDALUMNO
JOIN ASIGNATURA a2 
ON aa.IDASIGNATURA = a2.IDASIGNATURA
JOIN PROFESOR p 
ON a2.IDPROFESOR = p.IDPROFESOR
JOIN PERSONA p2 
ON p.DNI = p2.DNI
WHERE p2.NOMBRE LIKE 'Jorge' AND p2.APELLIDO LIKE 'Saenz';

-- 10
SELECT p2.dni, p2.nombre, p2.apellido FROM persona p JOIN profesor pr 
ON p.dni = pr.dni 
JOIN asignatura a 
ON pr.idprofesor = a.idprofesor
JOIN alumno_asignatura aa 
ON a.idasignatura = aa.idasignatura
JOIN alumno al 
ON aa.idalumno = al.idalumno
JOIN persona p2 
ON al.dni = p2.dni
WHERE p.nombre = 'Jorge' AND p.apellido = 'Saenz';

-- 11
SELECT t.NOMBRE  FROM TITULACION t JOIN ASIGNATURA a 
ON t.IDTITULACION = a.IDTITULACION
WHERE a.CREDITOS = 4;

-- 12
SELECT T.NOMBRE TITULO, a.NOMBRE ASIGNATURA, a.CREDITOS  FROM ASIGNATURA a JOIN TITULACION t 
ON a.IDTITULACION = t.IDTITULACION
WHERE a.CUATRIMESTRE = 1;

-- 13
SELECT a.NOMBRE ASIGNATURA, a.COSTEBASICO, P.NOMBRE PERSONA_MATRICULADA FROM ASIGNATURA a JOIN ALUMNO_ASIGNATURA aa 
ON a.IDASIGNATURA = aa.IDASIGNATURA
JOIN ALUMNO a2 
ON aa.IDALUMNO = a2.IDALUMNO
JOIN PERSONA p 
ON a2.DNI = p.DNI
WHERE a.COSTEBASICO > 4.5;


-- 14
SELECT P2.NOMBRE PROFESOR, A.NOMBRE ASIGNATURA FROM PROFESOR p JOIN PERSONA p2 
ON p.DNI = p2.DNI
JOIN ASIGNATURA a 
ON p.IDPROFESOR = a.IDPROFESOR
WHERE a.COSTEBASICO BETWEEN 25 AND 35;

-- 15
SELECT DISTINCT P.NOMBRE  FROM PERSONA P JOIN ALUMNO a 
ON P.DNI = A.DNI
JOIN ALUMNO_ASIGNATURA aa  
ON a.IDALUMNO = aa.IDALUMNO
WHERE aa.IDASIGNATURA LIKE '150212' OR aa.IDASIGNATURA LIKE '130113';

-- 16
SELECT T.NOMBRE TITULO, a.NOMBRE ASIGNATURA  FROM ASIGNATURA a JOIN TITULACION t 
ON a.IDTITULACION = t.IDTITULACION
WHERE a.CREDITOS != 6;

-- 17
SELECT a.NOMBRE ASIGNATURA, a.CREDITOS * 10 HORAS, a2.DNI  FROM ASIGNATURA a JOIN ALUMNO_ASIGNATURA aa 
ON a.IDASIGNATURA = aa.IDASIGNATURA
JOIN ALUMNO a2 
ON aa.IDALUMNO = a2.IDALUMNO
ORDER BY A.NOMBRE ASC;

-- 18
SELECT P.NOMBRE  FROM PERSONA p JOIN ALUMNO a 
ON p.DNI = a.DNI
JOIN ALUMNO_ASIGNATURA aa 
ON a.IDALUMNO = aa.IDALUMNO
WHERE p.VARON = 0 AND p.CIUDAD LIKE 'Sevilla';

-- 19
SELECT a.NOMBRE FROM ASIGNATURA a
WHERE a.IDPROFESOR LIKE 'P101';

-- 20
SELECT p.NOMBRE FROM PERSONA p JOIN ALUMNO a 
ON p.DNI = a.DNI
JOIN ALUMNO_ASIGNATURA aa 
ON a.IDALUMNO = aa.IDALUMNO
WHERE aa.NUMEROMATRICULA >= 3;

SELECT * FROM ALUMNO;
SELECT * FROM ALUMNO_ASIGNATURA;
SELECT * FROM ASIGNATURA;
SELECT * FROM PERSONA;
SELECT * FROM PROFESOR;
SELECT * FROM TITULACION;