-- 1
SELECT NOMBRE, CREDITOS FROM ASIGNATURA;

-- 2
SELECT DISTINCT CREDITOS FROM ASIGNATURA;

-- 3
SELECT * FROM PERSONA;

-- 4
SELECT NOMBRE, CREDITOS FROM ASIGNATURA
WHERE CUATRIMESTRE = 1;

-- 5
SELECT NOMBRE, APELLIDO FROM PERSONA
WHERE FECHA_NACIMIENTO > TO_DATE('1975/01/01', 'YYYY/MM/DD');

-- 6
SELECT NOMBRE, COSTEBASICO FROM ASIGNATURA
WHERE CREDITOS > 4.5;

-- 7
SELECT NOMBRE FROM ASIGNATURA
WHERE COSTEBASICO BETWEEN 25 AND 35;

-- 8
SELECT * FROM ALUMNO_ASIGNATURA
WHERE IDASIGNATURA LIKE '150212' OR IDASIGNATURA LIKE '130113';

-- 9
SELECT NOMBRE FROM ASIGNATURA
WHERE CUATRIMESTRE = 2 AND CREDITOS != 6;

-- 10
SELECT NOMBRE, APELLIDO FROM PERSONA
WHERE APELLIDO LIKE 'G%';

-- 11
SELECT NOMBRE FROM ASIGNATURA
WHERE IDTITULACION IS NULL;

-- 12
SELECT NOMBRE FROM ASIGNATURA
WHERE IDTITULACION IS NOT NULL;

-- 13
SELECT NOMBRE FROM ASIGNATURA
WHERE COSTEBASICO / CREDITOS > 8;

-- 14
SELECT NOMBRE, CREDITOS*10 NUM_HORAS FROM  ASIGNATURA;

-- 15
SELECT * FROM ASIGNATURA
WHERE CUATRIMESTRE = 2
ORDER BY IDASIGNATURA;

-- 16
SELECT NOMBRE FROM PERSONA
WHERE CIUDAD = 'Madrid' AND VARON = 0;

-- 17
SELECT NOMBRE, TELEFONO FROM PERSONA
WHERE TELEFONO LIKE '91%';

-- 18
SELECT NOMBRE FROM ASIGNATURA
WHERE LOWER(NOMBRE) LIKE '%pro%';

-- 19
SELECT NOMBRE FROM ASIGNATURA
WHERE CURSO = 1 AND IDPROFESOR = 'P101';

-- 20
SELECT IDALUMNO, IDASIGNATURA FROM ALUMNO_ASIGNATURA
WHERE NUMEROMATRICULA >= 3;

-- 21
SELECT NOMBRE, COSTEBASICO, 
COSTEBASICO * 1.10 PRIMERA_REP, 
COSTEBASICO * 1.30 SEGUNDA_REP, 
COSTEBASICO * 1.60 TERCERA_REP
FROM ASIGNATURA;

--22
SELECT * FROM PERSONA
WHERE FECHA_NACIMIENTO < TO_DATE('01/01/1970','DD/MM/YYYY');

--23
SELECT DISTINCT DNI FROM PROFESOR;

--24
SELECT IDALUMNO FROM ALUMNO_ASIGNATURA
WHERE IDASIGNATURA = '130122';

--25
SELECT DISTINCT IDASIGNATURA FROM ALUMNO_ASIGNATURA;

--26
SELECT NOMBRE FROM ASIGNATURA
WHERE CREDITOS > 4 AND (CUATRIMESTRE = 1 OR CURSO = 1);

--27
SELECT DISTINCT IDTITULACION FROM ASIGNATURA
WHERE IDTITULACION IS NOT NULL;

--28
SELECT DNI FROM PERSONA
WHERE LOWER(APELLIDO) LIKE '%g%';

--29
SELECT * FROM PERSONA
WHERE VARON = 1 AND FECHA_NACIMIENTO > TO_DATE('31/12/1970','DD/MM/YYYY')
AND CIUDAD LIKE 'M%';