CREATE TABLE PROFESOR
(
	DNI VARCHAR2(10) ,
	NOMBRE VARCHAR2(50),
	DIRECCION VARCHAR2 (50),
	TITULACION VARCHAR2 (50),
	SUELDO NUMBER(10,2),
	CONSTRAINT PK_PROFESOR PRIMARY KEY (DNI)
);

CREATE TABLE CURSO 
(
	CODIGO NUMBER(10),
	NOMBRE VARCHAR2(100),
	MAX_ALUMNOS NUMBER(4),
	DNI_PROFESOR VARCHAR2(10),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	HORAS NUMBER(5),
	CONSTRAINT PK_CURSO PRIMARY KEY (CODIGO),
	CONSTRAINT FK_CURSO_PROFESOR FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESOR(DNI) ON DELETE CASCADE
);

CREATE TABLE ALUMNOS
(
	DNI VARCHAR2 (10),
	NOMBRE VARCHAR2 (25),
	APELLIDOS VARCHAR2 (50),
	DIRECCION VARCHAR2(50),
	FECHA_NACIMIENTO DATE,
	SEXO VARCHAR2(5),
	CONSTRAINT PK_ALUMNOS PRIMARY KEY (DNI)
);

ALTER TABLE ALUMNOS ADD COD_CURSO NUMBER(10);
ALTER TABLE ALUMNOS ADD CONSTRAINT FK_ALUMNOS FOREIGN KEY (COD_CURSO) REFERENCES CURSO(CODIGO) ON DELETE CASCADE;

ALTER TABLE CURSO MODIFY HORAS NUMBER(5) NOT NULL;

ALTER TABLE PROFESOR MODIFY SUELDO NUMBER(10,2) NOT NULL;

ALTER TABLE CURSO MODIFY NOMBRE VARCHAR2(100) UNIQUE;

ALTER TABLE PROFESOR MODIFY NOMBRE VARCHAR2(50) UNIQUE;

ALTER TABLE CURSO ADD CONSTRAINT CHK_FECHAS CHECK (FECHA_INICIO < FECHA_FIN);

ALTER TABLE ALUMNOS ADD CONSTRAINT CHK_SEXO CHECK (SEXO IN('M', 'M'));

