CREATE TABLE FABRICANTE
(
	CODIGO NUMBER(10),
	NOMBRE VARCHAR2(100),
	CONSTRAINT PK_FABRICANTE PRIMARY KEY (CODIGO)
);

CREATE TABLE PRODUCTO
(
	CODIGO NUMBER(10),
	NOMBRE VARCHAR2(100),
	PRECIO NUMBER(10,2),
	COD_FABRICANTE NUMBER(10),
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO),
	CONSTRAINT FK_PRODCUTO FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTE(CODIGO)
);

INSERT INTO FABRICANTE VALUES (1, 'Asus');
INSERT INTO FABRICANTE VALUES (2, 'Lenovo');
INSERT INTO FABRICANTE VALUES (3, 'Hewlett-Packard');
INSERT INTO FABRICANTE VALUES (4, 'Samsung');
INSERT INTO FABRICANTE VALUES (5, 'Seagate');
INSERT INTO FABRICANTE VALUES (6, 'Crucial');
INSERT INTO FABRICANTE VALUES (7, 'Gigabyte');
INSERT INTO FABRICANTE VALUES (8, 'Huawei');
INSERT INTO FABRICANTE VALUES (9, 'Xiaomi');

INSERT INTO PRODUCTO VALUES (1, 'Disco duro SATA3 1TB', 86.99, 5);
INSERT INTO PRODUCTO VALUES (2, 'Memoria RAM DDR4 8GB', 120, 6);
INSERT INTO PRODUCTO VALUES (3, 'Disco SSD 1 TB', 150.99, 4);
INSERT INTO PRODUCTO VALUES (4, 'GeForce GTX 1050Ti', 185, 7);
INSERT INTO PRODUCTO VALUES (5, 'GeForce GTX 1080 Xtreme', 755, 6);
INSERT INTO PRODUCTO VALUES (6, 'Monitor 24 LED Full HD', 202, 1);
INSERT INTO PRODUCTO VALUES (7, 'Monitor 27 LED Full HD', 245.99, 1);
INSERT INTO PRODUCTO VALUES (8, 'Portátil Yoga 520', 559, 2);
INSERT INTO PRODUCTO VALUES (9, 'Portátil Ideapad 320', 444, 2);
INSERT INTO PRODUCTO VALUES (10, 'Impresora HP Deskjet 3720', 59.99, 3);
INSERT INTO PRODUCTO VALUES (11, 'Impresora HP Laserjet Pro M26nw', 180, 3);


--1
INSERT INTO FABRICANTE (CODIGO, NOMBRE) VALUES (10, 'MSI');

--2
-- ESTE DARIA ERROR YA QUE CODIGO ES LA PRIMARY KEY Y NO PUEDE SER NULL

--3
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, COD_FABRICANTE) VALUES (12, 'PLACA BASE MSI', 145, 10);

--4
-- DARIA ERROR PORQUE CODIGO ES LA PRIMARY KEY

--5
-- NO SERIA POSIBLE ELIMINARLO PORQUE ESTA ASOCIADO A PRODUCTO
-- PARA PODER ELIMINARLO HABRIA QUE ELIMINAR PRIMERO LOS PRODUCTOS ASOCIADOS CON EL FABRICANTE
DELETE FROM PRODUCTO WHERE COD_FABRICANTE = 1;
DELETE FROM FABRICANTE WHERE NOMBRE = 'Asus';

--6
DELETE FROM FABRICANTE WHERE NOMBRE = 'Xiaomi';

--7
-- NO ES POSIBLE YA QUE TIENE UN FK QUE LO BLOQUEA
-- UPDATE FABRICANTE SET CODIGO = 20 WHERE NOMBRE = 'Lenovo';

--8
UPDATE FABRICANTE SET CODIGO = 30 WHERE NOMBRE = 'Huawei';

--9
UPDATE PRODUCTO SET PRECIO = PRECIO + 5;

--10
DELETE FROM PRODUCTO WHERE NOMBRE LIKE 'Impresora%' AND PRECIO < 200;

SELECT * FROM FABRICANTE;
SELECT * FROM PRODUCTO;