CREATE TABLE DEPARTAMENTO (
    CODIGO NUMBER(10),
    NOMBRE VARCHAR2(100),
    PRESUPUESTO NUMBER(10,2),
    CONSTRAINT PK_DEPARTAMENTE PRIMARY KEY (CODIGO)
);

CREATE TABLE EMPLEADO (
    CODIGO NUMBER(10),
    NIF VARCHAR2(9),
    NOMBRE VARCHAR2(100),
    APELLIDO1 VARCHAR2(100),
    APELLIDO2 VARCHAR2(100),
    CODIGO_DEPARTAMENTO NUMBER (10),
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_EMPLEADO FOREIGN KEY (CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTO(CODIGO)
);

INSERT INTO DEPARTAMENTO VALUES (1, 'DESARROLLO', 120000);
INSERT INTO DEPARTAMENTO VALUES (2, 'SISTEMAS', 150000);
INSERT INTO DEPARTAMENTO VALUES (3, 'RECURSOS HUMANOS', 280000);
INSERT INTO DEPARTAMENTO VALUES (4, 'CONTABILIDAD', 110000);
INSERT INTO DEPARTAMENTO VALUES (5, 'I+D', 375000);
INSERT INTO DEPARTAMENTO VALUES (6, 'PROYECTOS', 0);
INSERT INTO DEPARTAMENTO VALUES (7, 'PUBLICIDAD', 0);

INSERT INTO EMPLEADO VALUES (1, '32481596F', 'AARÓN', 'RIVERO', 'GÓMEZ', 1);
INSERT INTO EMPLEADO VALUES (2, 'Y5575632D', 'ADELA', 'SALAS', 'DÍAZ', 2);
INSERT INTO EMPLEADO VALUES (3, 'R6970642B', 'ADOLFO', 'RUBIO', 'FLORES', 3);
INSERT INTO EMPLEADO VALUES (4, '77705545E', 'ADRIÁN', 'SUÁREZ', NULL, 4);
INSERT INTO EMPLEADO VALUES (5, '17087203C', 'MARCOS', 'LOYOLA', 'MÉNDEZ', 5);
INSERT INTO EMPLEADO VALUES (6, '38382980M', 'MARÍA', 'SANTANA', 'MORENO', 1);
INSERT INTO EMPLEADO VALUES (7, '80576669X', 'PILAR', 'RUIZ', NULL, 2);
INSERT INTO EMPLEADO VALUES (8, '71651431Z', 'PEPE', 'RUIZ', 'SANTANA', 3);
INSERT INTO EMPLEADO VALUES (9, '56399183D', 'JUAN', 'GÓMEZ', 'LÓPEZ', 2);
INSERT INTO EMPLEADO VALUES (10, '46384486H', 'DIEGO', 'FLORES', 'SALAS', 5);
INSERT INTO EMPLEADO VALUES (11, '67389283A', 'MARTA', 'HERRERA', 'GIL', 1);
INSERT INTO EMPLEADO VALUES (12, '41234836R', 'IRENE', 'SALAS', 'FLORES', NULL);
INSERT INTO EMPLEADO VALUES (13, '82635162B', 'JUAN ANTONIO', 'SÁEZ', 'GUERRERO', NULL);

--1
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE, PRESUPUESTO) VALUES (8, 'MARKETING', 10000);

--2 PARA QUE SEA POSIBLE HABRIA QUE CREAR UNA SECUENCIA PARA QUE VAYA INCREMENANDO LA PRIMARY KEY (CODIGO)
CREATE SEQUENCE SQ_INCREMENT START WITH 9 INCREMENT BY 1;
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE, PRESUPUESTO) VALUES (SQ_INCREMENT.NEXTVAL, 'BBDD', 20000);

--3 NO EXISTE LA COLUMNA GASTOS POR LO QUE HABRIA QUE CREARLA
ALTER TABLE DEPARTAMENTO ADD GASTOS NUMBER(10,2);
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE, PRESUPUESTO, GASTOS) VALUES (SQ_INCREMENT.NEXTVAL, 'DISEÑO', 50000, 5000);

--4
INSERT INTO EMPLEADO
VALUES (14, '99999999A', 'ALVARO', 'MARTÍN', 'CRUZ', 8);

--5 HABRIA QUE CREAR UNA SECUENCIA PARA QUE SEA POSIBLE
CREATE SEQUENCE SQ_EMPLEADO START WITH 15 INCREMENT BY 1;
INSERT INTO EMPLEADO (CODIGO, NIF, NOMBRE, APELLIDO1, APELLIDO2, CODIGO_DEPARTAMENTO) VALUES 
(SQ_EMPLEADO.NEXTVAL, '88888888B', 'JAVIER', 'MAKUMBA', 'MAD', 8);

--6
CREATE TABLE DEPARTAMENTO_BACKUP AS SELECT * FROM DEPARTAMENTO;

--7
DELETE FROM DEPARTAMENTO WHERE NOMBRE = 'PROYECTOS';

--8 NO SERIA POSIBLE HABRIA QUE BORRAR LA FOREIGN KEY Y CREARLA AÑADIENDO EL ON DELETE CASCADE AL FINAL
ALTER TABLE EMPLEADO DROP CONSTRAINT FK_EMPLEADO;

ALTER TABLE EMPLEADO ADD CONSTRAINT FK_EMPLEADO FOREIGN KEY (CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTO(CODIGO) ON DELETE CASCADE;

--9 NO SERIA POSIBLE YA QUE TIENE HIJOS POR LO QUE A LOS HIJOS LE ASIGNAMOS EL VALOR NULL
UPDATE EMPLEADO SET CODIGO_DEPARTAMENTO=NULL WHERE CODIGO_DEPARTAMENTO = 3;

UPDATE DEPARTAMENTO SET CODIGO = 30 WHERE CODIGO = 3;

--10
UPDATE DEPARTAMENTO SET CODIGO = 40 WHERE NOMBRE = 'PUBLICIDAD';

--11
UPDATE DEPARTAMENTO SET PRESUPUESTO = PRESUPUESTO + 50000 WHERE PRESUPUESTO < 20000;

--12
DELETE FROM EMPLEADO WHERE CODIGO_DEPARTAMENTO IS NULL;