CREATE TABLE FACTURA(
	ID NUMBER(10),
	PRECIO NUMBER(10,2),
	CONSTRAINT PK_FACTURA PRIMARY KEY (ID)
);

INSERT INTO FACTURA VALUES (1,10);
SELECT * FROM FACTURA;

INSERT INTO FACTURA VALUES (1, 'Ana');
INSERT INTO FACTURA VALUES (2, 'Luis');

SAVEPOINT 1;

INSERT INTO FACTURA VALUES (3, 'María');
INSERT INTO FACTURA VALUES (4, 'Carlos');

SAVEPOINT 2;

INSERT INTO FACTURA VALUES (5, 'Lucía');