-- 1
CREATE OR REPLACE PROCEDURE info
AS
	NUM_EMPLEADOS NUMBER;
	MIN_SALARIO NUMBER;
	MAX_SALARIO NUMBER;
	AVG_SALARIO NUMBER;
BEGIN
	SELECT COUNT(e.NUMDE), MIN(e.SALAR), MAX(e.SALAR), AVG(e.SALAR)
	INTO NUM_EMPLEADOS, MIN_SALARIO, MAX_SALARIO, AVG_SALARIO
	FROM DEPARTAMENTOS d
	JOIN EMPLEADOS e
	ON d.NUMDE = e.NUMDE
	WHERE d.NOMDE = 'FINANZAS';

	DBMS_OUTPUT.PUT_LINE ('Empleados trabajando: ' || NUM_EMPLEADOS);
	DBMS_OUTPUT.PUT_LINE ('Salario minimo: ' || MIN_SALARIO);
	DBMS_OUTPUT.PUT_LINE ('Salario maximo: ' || MAX_SALARIO);
	DBMS_OUTPUT.PUT_LINE ('Salario medio: ' || AVG_SALARIO);
END;

BEGIN
	info;
END;

-- 2
CREATE OR REPLACE PROCEDURE subir_salario
AS
	CURSOR c_empleados IS
	SELECT e.NUMEM, e.NOMEM, e.SALAR
	FROM EMPLEADOS e
	WHERE e.NUMHI > 2 AND e.SALAR < 2000;
	v_salariofinal NUMBER;
BEGIN
	FOR registro IN c_empleados
	LOOP
	v_salariofinal := registro.SALAR * 1.10;
	UPDATE EMPLEADOS e
	SET e.SALAR = registro.SALAR
	WHERE e.NUMEM = registro.NUMEM;
	DBMS_OUTPUT.PUT_LINE('Código empleado; ' || registro.NUMEM);
	DBMS_OUTPUT.PUT_LINE('Nombre empleado; ' || registro.NOMEM);
	DBMS_OUTPUT.PUT_LINE('Salario anterior; ' || registro.SALAR);
	DBMS_OUTPUT.PUT_LINE('Salario nuevo; ' || v_salariofinal);
	DBMS_OUTPUT.PUT_LINE('-----------');
	END LOOP;
END;

BEGIN
	subir_salario;
END;

-- 3
CREATE OR REPLACE PROCEDURE CONT_EMPLEADOS(NUM_DEP NUMBER, NUM_HIJOS NUMBER)
AS
	CURSOR NUM_EMPLEADOS IS
	SELECT COUNT(NUMEM) FROM EMPLEADOS
	WHERE NUMDEP = NUM_DEP AND NUM_HIJOS = NUMHI;
BEGIN
	DBMS_OUTPUT.PUT_LINE(NUM_EMPLEADOS);
END;

BEGIN
	CONT_EMPLEADOS(121, 3);
END;

SELECT * FROM EMPLEADOS;
SELECT e.NOMEM, e.NUMHI FROM EMPLEADOS e
	WHERE e.NUMDE  = 121 AND e.NUMHI  = 3;
