-- 1
CREATE OR REPLACE PROCEDURE EMPRESA.primero (dep NUMBER)
AS
	V_NOM VARCHAR2(14);
	V_LOC VARCHAR2(13);
BEGIN
	SELECT DNAME, LOC INTO V_NOM, V_LOC
	FROM DEPT WHERE DEPTNO = dep;

	DBMS_OUTPUT.PUT_LINE('DEP: ' || V_NOM);
	DBMS_OUTPUT.PUT_LINE('UBICADO EN: ' || V_LOC);
	
	EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('Departamento no existe');
END;


BEGIN
	primero(1);
END;

-- 2
CREATE OR REPLACE FUNCTION SALARIOS(DEP NUMBER)
RETURN NUMBER
IS
	V_SUM NUMBER := 0;
	CURSOR EMPLEADOS IS
	SELECT SAL FROM EMP
	WHERE DEPTNO = DEP;
BEGIN
	FOR EMPLEADO IN EMPLEADOS
	LOOP
		V_SUM := V_SUM + EMPLEADO;
	END LOOP;

	DBMS_OUTPUT.PUT_LINE(V_SUM);
END;

SELECT SALARIOS(10) FROM DUAL;

-- 3
CREATE OR REPLACE PROCEDURE MOSTRARABREVIATURAS
AS
	CURSOR EMPLEADOS IS
	SELECT ENAME FROM EMP;
	
BEGIN
	FOR EMPLEADO IN EMPLEADOS
	LOOP
		DBMS_OUTPUT.PUT_LINE(SUBSTR(EMPLEADO.ENAME,1,3));
	END LOOP;
END;

BEGIN
	MOSTRARABREVIATURAS;
END;

-- 4
CREATE OR REPLACE PROCEDURE TODOSDEP(DEP NUMBER)
IS
	CURSOR EMPLEADOS IS
	SELECT ENAME FROM EMP
	WHERE DEPTNO = DEP;
BEGIN
	FOR EMPLEADO IN EMPLEADOS
	LOOP
		DBMS_OUTPUT.PUT_LINE(EMPLEADO.ENAME);
	END LOOP;
END;

BEGIN
	TODOSDEP(10);
END;

-- 5
