-- 1
CREATE OR REPLACE PROCEDURE LAKRO.ESCRIBE
AS
BEGIN
	DBMS_OUTPUT.PUT_LINE('HOLA MUNDO');
END;

BEGIN
	ESCRIBE;
END;

-- 2
CREATE OR REPLACE PROCEDURE LAKRO.ESCRIBE_MENSAJE(TEXTO VARCHAR2)
AS
BEGIN
	DBMS_OUTPUT.PUT_LINE(TEXTO);
END;

BEGIN
	ESCRIBE_MENSAJE('ALVARO');
END;

-- 3
CREATE OR REPLACE PROCEDURE LAKRO.SERIE(MINIMO NUMBER, MAXIMO NUMBER, PASO NUMBER)
AS
	ACTUAL NUMBER(10) := MINIMO;
BEGIN
	WHILE ACTUAL <= MAXIMO LOOP
	DBMS_OUTPUT.PUT_LINE(ACTUAL);
	ACTUAL := ACTUAL + PASO;
	END LOOP;
END;

BEGIN
	SERIE(0,10,2);
END;

-- 4
CREATE OR REPLACE FUNCTION LAKRO.AZAR(MINIMO NUMBER, MAXIMO NUMBER)
RETURN NUMBER
IS
BEGIN
	RETURN TRUNC(DBMS_RANDOM.VALUE(MINIMO, MAXIMO));
END;

SELECT AZAR(1,100) FROM DUAL;

-- 5
CREATE OR REPLACE FUNCTION LAKRO.NOTA(NOTA NUMBER)
RETURN VARCHAR2
IS
BEGIN
	IF NOTA < 5 THEN
	DBMS_OUTPUT.PUT_LINE('INSUFICIENTE');
	ELSIF NOTA = 5 THEN
	DBMS_OUTPUT.PUT_LINE('SUFICIENTE');
	ELSIF NOTA = 6 OR NOTA = 7 THEN 
	DBMS_OUTPUT.PUT_LINE('BIEN');
	ELSIF NOTA = 8 OR NOTA = 9 THEN
	DBMS_OUTPUT.PUT_LINE('NOTABLE');
	ELSIF NOTA = 10 THEN
	DBMS_OUTPUT.PUT_LINE('SOBRSALIENTE');
	ELSE
	DBMS_OUTPUT.PUT_LINE('NOTA INCORRECTA');
	END IF;
END;

SELECT NOTA(5) FROM DUAL;

