-- 1
CREATE OR REPLACE PROCEDURE info
AS
	NUM_EMPLEADOS NUMBER;
	MIN_SALARIO NUMBER;
	MAX_SALARIO NUMBER;
	AVG_SALARIO NUMBER;
BEGIN
	SELECT COUNT(e.NUMDE), MIN(e.SALAR), MAX(e.SALAR), AVG(e.SALAR)
	INTO NUM_EMPLEADOS, MIN_SALARIO, MAX_SALARIO, AVG_SALARIO
	FROM DEPARTAMENTOS d
	JOIN EMPLEADOS e
	ON d.NUMDE = e.NUMDE
	WHERE d.NOMDE = 'FINANZAS';

	DBMS_OUTPUT.PUT_LINE ('Empleados trabajando: ' || NUM_EMPLEADOS);
	DBMS_OUTPUT.PUT_LINE ('Salario minimo: ' || MIN_SALARIO);
	DBMS_OUTPUT.PUT_LINE ('Salario maximo: ' || MAX_SALARIO);
	DBMS_OUTPUT.PUT_LINE ('Salario medio: ' || AVG_SALARIO);
END;

BEGIN
	info;
END;

-- 2
CREATE OR REPLACE PROCEDURE subir_salario
AS
	CURSOR c_empleados IS
	SELECT e.NUMEM, e.NOMEM, e.SALAR
	FROM EMPLEADOS e
	WHERE e.NUMHI > 2 AND e.SALAR < 2000;
	v_salariofinal NUMBER;
BEGIN
	FOR registro IN c_empleados
	LOOP
	v_salariofinal := registro.SALAR * 1.10;
	UPDATE EMPLEADOS e
	SET e.SALAR = registro.SALAR
	WHERE e.NUMEM = registro.NUMEM;
	DBMS_OUTPUT.PUT_LINE('Código empleado; ' || registro.NUMEM);
	DBMS_OUTPUT.PUT_LINE('Nombre empleado; ' || registro.NOMEM);
	DBMS_OUTPUT.PUT_LINE('Salario anterior; ' || registro.SALAR);
	DBMS_OUTPUT.PUT_LINE('Salario nuevo; ' || v_salariofinal);
	DBMS_OUTPUT.PUT_LINE('-----------');
	END LOOP;
END;

BEGIN
	subir_salario;
END;

-- 3
CREATE OR REPLACE PROCEDURE ALVARO.CONT_EMPLEADOS(NUM_DEP NUMBER, NUM_HIJOS NUMBER)
AS
	CURSOR NUM_EMPLEADOS(v_dep NUMBER, v_hijos NUMBER) IS
	SELECT NOMEM FROM EMPLEADOS
	WHERE NUMDE = v_dep AND NUMHI = v_hijos;

	v_contador NUMBER := 0;
BEGIN
	FOR empleados IN NUM_EMPLEADOS(NUM_DEP, NUM_HIJOS)
	LOOP
		v_contador := v_contador + 1;
		
	END LOOP;
	
	DBMS_OUTPUT.PUT_LINE(v_contador);
END;

BEGIN
	CONT_EMPLEADOS(121, 3);
END;

-- 4
CREATE OR REPLACE PROCEDURE ALVARO.EDAD_EMP(NOM VARCHAR2)
AS
	FECHA DATE;
	V_ANIOS NUMBER;
	V_MESES NUMBER;
	V_DIAS NUMBER;
BEGIN
	SELECT FECNA INTO FECHA FROM EMPLEADOS
	WHERE UPPER(NOMEM) = UPPER(NOM);
	
	V_ANIOS := TRUNC(MONTHS_BETWEEN(SYSDATE, FECHA) / 12);
	V_MESES := TRUNC(MOD(MONTHS_BETWEEN(SYSDATE, FECHA), 12));
	V_DIAS := TRUNC(SYSDATE - ADD_MONTHS(FECHA, TRUNC(MONTHS_BETWEEN(SYSDATE, FECHA))));
	
	DBMS_OUTPUT.PUT_LINE(FECHA);
	DBMS_OUTPUT.PUT_LINE(V_ANIOS);
	DBMS_OUTPUT.PUT_LINE(V_MESES);
	DBMS_OUTPUT.PUT_LINE(V_DIAS);
END;

BEGIN
	EDAD_EMP('CESAR');
END;

