CREATE TABLE BIBLIOTECARIO (
    COD_BIBLIOTECARIO NUMBER(10),
    NOMBRE VARCHAR2(50),
    TURNO VARCHAR2(20) DEFAULT 'MAÑANA',
    COD_JEFE NUMBER(10),
    CONSTRAINT PK_BIBLIOTECARIO PRIMARY KEY (COD_BIBLIOTECARIO),
    CONSTRAINT FK_BIBLIOTECARIO FOREIGN KEY (COD_JEFE) REFERENCES BIBLIOTECARIO(COD_BIBLIOTECARIO) ON DELETE SET NULL
);

CREATE TABLE LECTOR (
    COD_LECTOR NUMBER(10),
    DNI VARCHAR2(9),
    NOMBRE VARCHAR2(50),
    SEXO VARCHAR2(1),
    CONSTRAINT PK_LECTO PRIMARY KEY (COD_LECTOR)
);

CREATE TABLE LIBRO (
    COD_LIBRO NUMBER(10),
    TITULO VARCHAR2(100),
    NUM_PAGINAS NUMBER(10),
    CONSTRAINT PK_LIBRO PRIMARY KEY (COD_LIBRO)
);

CREATE TABLE PRESTAMO (
    COD_PRESTAMO NUMBER(10),
    COD_LECTOR NUMBER(10),
    COD_LIBRO NUMBER(10),
    FECHA_PRESTAMO DATE DEFAULT SYSDATE,
    FECHA_DEVOLUCION DATE,
    CONSTRAINT PK_PRESTAMO PRIMARY KEY (COD_PRESTAMO),
    CONSTRAINT FK1_PRESTAMO FOREIGN KEY (COD_LECTOR) REFERENCES LECTOR(COD_LECTOR) ON DELETE CASCADE,
    CONSTRAINT FK2_PRESTAMO FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO(COD_LIBRO)
);

CREATE TABLE ATENCION 
(
    COD_BIBLIOTECARIO NUMBER(10),
	COD_LECTOR NUMBER(10),
    FECHA DATE,
    OBSERVACIONES VARCHAR2(500),
    CONSTRAINT PK_ATENCION PRIMARY KEY (COD_BIBLIOTECARIO, COD_LECTOR),
    CONSTRAINT FK1_ATENCION FOREIGN KEY (COD_BIBLIOTECARIO) REFERENCES BIBLIOTECARIO(COD_BIBLIOTECARIO) ON DELETE CASCADE,
    CONSTRAINT FK2_ATENCION FOREIGN KEY (COD_LECTOR) REFERENCES LECTOR(COD_LECTOR) ON DELETE CASCADE
);

-- APARTADO 1
-- 1
-- CON UN DEFAULT SYSDATE

-- 2
ALTER TABLE LIBRO ADD CONSTRAINT CHK_PAGINAS CHECK (NUM_PAGINAS > 10);

-- 3
ALTER TABLE PRESTAMO ADD CONSTRAINT CHK_PRESTAMO CHECK (FECHA_DEVOLUCION > FECHA_PRESTAMO);

-- 4
-- CON UN DEFAULT 'MAÑANA'

-- 5
-- CON LA FOREIGN KEY YA VALDRIA

-- 6
-- AÑADIENDO ON DELETE SET NULL A LA FOREIGN KEY

-- 7
-- CON UN DELETE ON CASCADE EN LAS FOREIGN KEYS

-- 8
-- CON UN DELETE ON CASCADE EN LAS FOREIGN KEYS

-- APARTADO 2
-- 1
ALTER TABLE LECTOR ADD CONSTRAINT CHK_SEXO CHECK (SEXO IN ('H','M'));

-- 2
-- PORQUE LOS DOS ESTAN COMO PRIMARY KEY EN LA TABLA ATENCION
-- PARA ARREGLARLO QUITO COD_LECTOR DE LA PRIMARY KEY Y DEJO COD_BIBLIOTECARIO COMO PRIMARY KEY SOLAMENTE
ALTER TABLE ATENCION DROP CONSTRAINT PK_ATENCION;
ALTER TABLE ATENCION ADD CONSTRAINT PK_ATENCION PRIMARY KEY (COD_BIBLIOTECARIO);

-- 3
ALTER TABLE LECTOR MODIFY DNI VARCHAR2(12);

-- 4
INSERT INTO BIBLIOTECARIO (COD_BIBLIOTECARIO, NOMBRE) VALUES (1,'ALVARO');

INSERT INTO LECTOR (COD_LECTOR, NOMBRE) VALUES (1,'JAVIER');
INSERT INTO LECTOR (COD_LECTOR, NOMBRE) VALUES (2,'DANIEL');

-- 5
INSERT INTO LIBRO (COD_LIBRO, NUM_PAGINAS) VALUES (1,120);

-- 6
INSERT INTO PRESTAMO VALUES (1,1,1,SYSDATE,NULL);

-- 7
INSERT INTO ATENCION VALUES (1,1,SYSDATE,NULL);

-- 8
ALTER TABLE ATENCION ADD FECHA_PROXIMA_VISITA DATE;

-- 9
UPDATE LECTOR SET NOMBRE = 'ANA GARCIA', SEXO = 'M' WHERE COD_LECTOR = 1;

-- 10
DELETE FROM LECTOR WHERE COD_LECTOR = 1;

-- 11
DROP TABLE BIBLIOTECARIO CASCADE CONSTRAINT;
DROP TABLE LECTOR CASCADE CONSTRAINT;
DROP TABLE LIBRO CASCADE CONSTRAINT;
DROP TABLE PRESTAMO CASCADE CONSTRAINT;
DROP TABLE ATENCION CASCADE CONSTRAINT;