--1
CREATE TABLE CABALLOS
(
	CODCABALLOS VARCHAR2(4),
	NOMBRE VARCHAR2(20) NOT NULL,
	PESO NUMBER(3),
	FECHA_NACIMIENTO DATE,
	PROPIETARIO VARCHAR2(25),
	NACIONALIDAD VARCHAR2(20),
	CONSTRAINT PK_CABALLOS PRIMARY KEY (CODCABALLOS),
	CONSTRAINT CHK_PESO CHECK (PESO BEETWEN (240 AND 300)),
	CONSTRAINT CHK_FECHA CHECK (),
	CONSTRAINT CHK_NACIONALIDAD CHECK (NACIONALIDAD.UPPER())
);

CREATE TABLE CARRERAS
(
	CODCARRERA VARCHAR2(4),
	FECHA_HORA DATE,
	IMPORTE_PREMIO NUMBER(6),
	APUESTA_LIMITE NUMBER(5,2),
	CONSTRAINT PK_CARRERAS PRIMARY KEY (CODCARRERA),
	CONSTRAINT CHK_APUESTA CHECK (APUESTA_LIMITE < 20000)
);

CREATE TABLE CLIENTES
(
	DNI VARCHAR2(9),
	NOMBRE VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI),
	CONSTRAINT CHK_DNI CHECK (REGEXP_LIKE(^[0-9]{8}[A-Z]{1}$)),
	CONSTRAINT CHK_NACIONALIDAD CHECK (NACIONALIDAD.UPPER()
);

CREATE TABLE PARTICIPACIONES
(
	CODCABALLO VARCHAR2(4),
	CODCARRERA VARCHAR2(4),
	DORSAL NUMBER(2) NOT NULL,
	JOCKEY VARCHAR2(10) NOT NULL,
	POSICIONFINAL NUMBER(2),
	CONSTRAINT PK_PARTICIPACIONES PRIMARY KEY (CODCARRERA),
	CONSTRAINT FK1_PARTICIPACIONES FOREIGN KEY (CODCABALLO) REFERENCES CABALLOS(CODCABALLO) ON DELETE CASCADE,
	CONSTRAINT FK2_PARTICIPACIONES FOREIGN KEY (CODCARRERA) REFERENCES CARRERAR(CODCARRERA) ON DELETE CASCADE
);

CREATE TABLE APUESTAS
(
	DNICLIENTE VARCHAR2(10),
	CODCABALLO VARCHAR2(4),
	CODCARRERA VARCHAR2(4),
	IMPORTE NUMBER(6) DEFAULT 300 NOT NULL ,
	TANTOPORUNO NUMBER(4,2),
	CONSTRAINT PK_APUESTAS PRIMARY KEY (DNICLIENTE),
	CONSTRAINT FK1_APUESTAS FOREIGN KEY (CODCABALLO) REFERENCES CABALLOS(CODCABALLO),
	CONSTRAINT FK2_APUESTAS FOREIGN KEY (CODCARRERA) REFERENCES CARRERAS(CODCARRERA),
	CONSTRAINT CHK_TANTOPORUNO CHECK (TANTOPORUNO > 1)
);

INSERT INTO CLIENTES VALUES ("1111111Q", "DREW", "ESCOCIA");



